type=command
command=bash ./SubmitJob.sh "LVS" "/datashare/mkttracking/jobs/tracking/sparknrt/bin/prod" "./dedupeAndSink.sh EPN marketing.tracking.ssl.filtered-epn viewfs://apollo-rno/user/b_marketing_tracking/tracking-events-workdir
 viewfs://apollo-rno/user/b_marketing_tracking/tracking-events http://chocolateclusteres-app-private-11.stratus.lvs.ebay.com:9200 1 true"
failure.emails=jialili1@ebay.com, fechen@ebay.com, xiangli4@ebay.com, yliu29@ebay.com, huiclu@ebay.com, shuangxu@ebay.com, lxiong1@ebay.com, zhofan@ebay.com, zjian@ebay.com, zhiyuawang@ebay.com