- name: EP
  doneFilePrefix: utp_event_hourly.ep.done.
  condition: channelType in ('MRKT_EMAIL', 'SITE_EMAIL', 'MOBILE_NOTIF', 'HUB_NOTIF')
- name: all
  doneFilePrefix: utp_event_hourly.done.
  condition: 1=1