package com.ebay.traffic.chocolate.sparknrt.compare

import com.ebay.traffic.chocolate.sparknrt.BaseSparkNrtJob
import com.ebay.traffic.chocolate.sparknrt.common.schema.TableSchema
import org.apache.hadoop.fs.{FSDataOutputStream, Path}
import org.apache.spark.sql.functions.{col, udf}

class ImpressionCompare(params: Parameter) extends BaseSparkNrtJob(params.appName, params.mode) {
  import spark.implicits._

  override def run(): Unit = {
    val our_schema = TableSchema("df_epn_impression.json")
    val your_schema = TableSchema("df_your_epn_impression.json")

    val removeParamsUdf = udf(removeParams(_: String))
    val normalizeUrlUdf = udf((roverUrl: String) => normalizeUrl(roverUrl))

    val ourDf = readFilesAsDF(params.impression_source, our_schema.dfSchema, "csv", "tab", false)
      .withColumn("my_uri", removeParamsUdf($"ROVER_URL_TXT"))
      .dropDuplicates("my_uri", "CRLTN_GUID_TXT")
    val yourDf = readFilesAsDF(params.impression_dest, your_schema.dfSchema, "csv", "tab", false)
      .withColumn("your_uri", normalizeUrlUdf(col("y_ROVER_URL_TXT")))
      .dropDuplicates("your_uri", "y_CRLTN_GUID_TXT")
    val verifyResultUdf = udf(verifyResult(_: String, _: String))
    val verifyClick_TSResultUdf = udf(verifyClick_TSResult(_: String, _: String))



    var df = ourDf.join(yourDf, $"my_uri" === $"your_uri" && $"CRLTN_GUID_TXT" === $"y_CRLTN_GUID_TXT", "inner")
      .withColumn("c_IMPRSN_CNTNR_ID", verifyResultUdf($"IMPRSN_CNTNR_ID", $"y_IMPRSN_CNTNR_ID")).drop("IMPRSN_CNTNR_ID").drop("y_IMPRSN_CNTNR_ID")
      .withColumn("c_FILE_SCHM_VRSN_NUM", verifyResultUdf($"FILE_SCHM_VRSN_NUM", $"y_FILE_SCHM_VRSN_NUM")).drop("FILE_SCHM_VRSN_NUM").drop("y_FILE_SCHM_VRSN_NUM")
      .withColumn("c_FILE_ID", verifyResultUdf($"FILE_ID", $"y_FILE_ID")).drop("FILE_ID").drop("y_FILE_ID")
      .withColumn("c_BATCH_ID", verifyResultUdf($"BATCH_ID", $"y_BATCH_ID")).drop("BATCH_ID").drop("y_BATCH_ID")
      .withColumn("c_CHNL_ID", verifyResultUdf($"CHNL_ID", $"y_CHNL_ID")).drop("CHNL_ID").drop("y_CHNL_ID")
      .withColumn("c_CRLTN_GUID_TXT", verifyResultUdf($"CRLTN_GUID_TXT", $"y_CRLTN_GUID_TXT")).drop("CRLTN_GUID_TXT").drop("y_CRLTN_GUID_TXT")
      .withColumn("c_GUID_TXT", verifyResultUdf($"GUID_TXT", $"y_GUID_TXT")).drop("GUID_TXT").drop("y_GUID_TXT")
      .withColumn("c_USER_ID", verifyResultUdf($"USER_ID", $"y_USER_ID")).drop("USER_ID").drop("y_USER_ID")
      .withColumn("c_CLNT_RMT_IP", verifyResultUdf($"CLNT_RMT_IP", $"y_CLNT_RMT_IP")).drop("CLNT_RMT_IP").drop("y_CLNT_RMT_IP")
      .withColumn("c_BRWSR_TYPE_NUM", verifyResultUdf($"BRWSR_TYPE_NUM", $"y_BRWSR_TYPE_NUM")).drop("BRWSR_TYPE_NUM").drop("y_BRWSR_TYPE_NUM")
      .withColumn("c_BRWSR_NAME", verifyResultUdf($"BRWSR_NAME", $"y_BRWSR_NAME")).drop("BRWSR_NAME").drop("y_BRWSR_NAME")
      .withColumn("c_RFR_URL_NAME", verifyResultUdf($"RFR_URL_NAME", $"y_RFR_URL_NAME")).drop("RFR_URL_NAME").drop("y_RFR_URL_NAME")
      .withColumn("c_PRVS_RFR_DMN_NAME", verifyResultUdf($"PRVS_RFR_DMN_NAME", $"y_PRVS_RFR_DMN_NAME")).drop("PRVS_RFR_DMN_NAME").drop("y_PRVS_RFR_DMN_NAME")
      .withColumn("c_USER_QUERY_TXT", verifyResultUdf($"USER_QUERY_TXT", $"y_USER_QUERY_TXT")).drop("USER_QUERY_TXT").drop("y_USER_QUERY_TXT")
      .withColumn("c_PLCMNT_DATA_TXT", verifyResultUdf($"PLCMNT_DATA_TXT", $"y_PLCMNT_DATA_TXT")).drop("PLCMNT_DATA_TXT").drop("y_PLCMNT_DATA_TXT")
      .withColumn("c_PBLSHR_ID", verifyResultUdf($"PBLSHR_ID", $"y_PBLSHR_ID")).drop("PBLSHR_ID").drop("y_PBLSHR_ID")
      .withColumn("c_AMS_PBLSHR_CMPGN_ID", verifyResultUdf($"AMS_PBLSHR_CMPGN_ID", $"y_AMS_PBLSHR_CMPGN_ID")).drop("AMS_PBLSHR_CMPGN_ID").drop("y_AMS_PBLSHR_CMPGN_ID")
      .withColumn("c_AMS_TOOL_ID", verifyResultUdf($"AMS_TOOL_ID", $"y_AMS_TOOL_ID")).drop("AMS_TOOL_ID").drop("y_AMS_TOOL_ID")
      .withColumn("c_CSTM_ID", verifyResultUdf($"CSTM_ID", $"y_CSTM_ID")).drop("CSTM_ID").drop("y_CSTM_ID")
      .withColumn("c_FLEX_FLD_VRSN_NUM", verifyResultUdf($"FLEX_FLD_VRSN_NUM", $"y_FLEX_FLD_VRSN_NUM")).drop("FLEX_FLD_VRSN_NUM").drop("y_FLEX_FLD_VRSN_NUM")
      .withColumn("c_FLEX_FLD_1_TXT", verifyResultUdf($"FLEX_FLD_1_TXT", $"y_FLEX_FLD_1_TXT")).drop("FLEX_FLD_1_TXT").drop("y_FLEX_FLD_1_TXT")
      .withColumn("c_FLEX_FLD_2_TXT", verifyResultUdf($"FLEX_FLD_2_TXT", $"y_FLEX_FLD_2_TXT")).drop("FLEX_FLD_2_TXT").drop("y_FLEX_FLD_2_TXT")
      .withColumn("c_FLEX_FLD_3_TXT", verifyResultUdf($"FLEX_FLD_3_TXT", $"y_FLEX_FLD_3_TXT")).drop("FLEX_FLD_3_TXT").drop("y_FLEX_FLD_3_TXT")
      .withColumn("c_FLEX_FLD_4_TXT", verifyResultUdf($"FLEX_FLD_4_TXT", $"y_FLEX_FLD_4_TXT")).drop("FLEX_FLD_4_TXT").drop("y_FLEX_FLD_4_TXT")
      .withColumn("c_FLEX_FLD_5_TXT", verifyResultUdf($"FLEX_FLD_5_TXT", $"y_FLEX_FLD_5_TXT")).drop("FLEX_FLD_5_TXT").drop("y_FLEX_FLD_5_TXT")
      .withColumn("c_FLEX_FLD_6_TXT", verifyResultUdf($"FLEX_FLD_6_TXT", $"y_FLEX_FLD_6_TXT")).drop("FLEX_FLD_6_TXT").drop("y_FLEX_FLD_6_TXT")
      .withColumn("c_FLEX_FLD_7_TXT", verifyResultUdf($"FLEX_FLD_7_TXT", $"y_FLEX_FLD_7_TXT")).drop("FLEX_FLD_7_TXT").drop("y_FLEX_FLD_7_TXT")
      .withColumn("c_FLEX_FLD_8_TXT", verifyResultUdf($"FLEX_FLD_8_TXT", $"y_FLEX_FLD_8_TXT")).drop("FLEX_FLD_8_TXT").drop("y_FLEX_FLD_8_TXT")
      .withColumn("c_FLEX_FLD_9_TXT", verifyResultUdf($"FLEX_FLD_9_TXT", $"y_FLEX_FLD_9_TXT")).drop("FLEX_FLD_9_TXT").drop("y_FLEX_FLD_9_TXT")
      .withColumn("c_FLEX_FLD_10_TXT", verifyResultUdf($"FLEX_FLD_10_TXT", $"y_FLEX_FLD_10_TXT")).drop("FLEX_FLD_10_TXT").drop("y_FLEX_FLD_10_TXT")
      .withColumn("c_FLEX_FLD_11_TXT", verifyResultUdf($"FLEX_FLD_11_TXT", $"y_FLEX_FLD_11_TXT")).drop("FLEX_FLD_11_TXT").drop("y_FLEX_FLD_11_TXT")
      .withColumn("c_FLEX_FLD_12_TXT", verifyResultUdf($"FLEX_FLD_12_TXT", $"y_FLEX_FLD_12_TXT")).drop("FLEX_FLD_12_TXT").drop("y_FLEX_FLD_12_TXT")
      .withColumn("c_FLEX_FLD_13_TXT", verifyResultUdf($"FLEX_FLD_13_TXT", $"y_FLEX_FLD_13_TXT")).drop("FLEX_FLD_13_TXT").drop("y_FLEX_FLD_13_TXT")
      .withColumn("c_FLEX_FLD_14_TXT", verifyResultUdf($"FLEX_FLD_14_TXT", $"y_FLEX_FLD_14_TXT")).drop("FLEX_FLD_14_TXT").drop("y_FLEX_FLD_14_TXT")
      .withColumn("c_FLEX_FLD_15_TXT", verifyResultUdf($"FLEX_FLD_15_TXT", $"y_FLEX_FLD_15_TXT")).drop("FLEX_FLD_15_TXT").drop("y_FLEX_FLD_15_TXT")
      .withColumn("c_FLEX_FLD_16_TXT", verifyResultUdf($"FLEX_FLD_16_TXT", $"y_FLEX_FLD_16_TXT")).drop("FLEX_FLD_16_TXT").drop("y_FLEX_FLD_16_TXT")
      .withColumn("c_FLEX_FLD_17_TXT", verifyResultUdf($"FLEX_FLD_17_TXT", $"y_FLEX_FLD_17_TXT")).drop("FLEX_FLD_17_TXT").drop("y_FLEX_FLD_17_TXT")
      .withColumn("c_FLEX_FLD_18_TXT", verifyResultUdf($"FLEX_FLD_18_TXT", $"y_FLEX_FLD_18_TXT")).drop("FLEX_FLD_18_TXT").drop("y_FLEX_FLD_18_TXT")
      .withColumn("c_FLEX_FLD_19_TXT", verifyResultUdf($"FLEX_FLD_19_TXT", $"y_FLEX_FLD_19_TXT")).drop("FLEX_FLD_19_TXT").drop("y_FLEX_FLD_19_TXT")
      .withColumn("c_FLEX_FLD_20_TXT", verifyResultUdf($"FLEX_FLD_20_TXT", $"y_FLEX_FLD_20_TXT")).drop("FLEX_FLD_20_TXT").drop("y_FLEX_FLD_20_TXT")
      .withColumn("c_CTX_TXT", verifyResultUdf($"CTX_TXT", $"y_CTX_TXT")).drop("CTX_TXT").drop("y_CTX_TXT")
      .withColumn("c_CTX_CLD_TXT", verifyResultUdf($"CTX_CLD_TXT", $"y_CTX_CLD_TXT")).drop("CTX_CLD_TXT").drop("y_CTX_CLD_TXT")
      .withColumn("c_CTX_RSLT_TXT", verifyResultUdf($"CTX_RSLT_TXT", $"y_CTX_RSLT_TXT")).drop("CTX_RSLT_TXT").drop("y_CTX_RSLT_TXT")
      .withColumn("c_RFR_DMN_NAME", verifyResultUdf($"RFR_DMN_NAME", $"y_RFR_DMN_NAME")).drop("RFR_DMN_NAME").drop("y_RFR_DMN_NAME")
      .withColumn("c_IMPRSN_TS", verifyClick_TSResultUdf($"IMPRSN_TS", $"y_IMPRSN_TS")).drop("IMPRSN_TS").drop("y_IMPRSN_TS")
      .withColumn("c_AMS_PRGRM_ID", verifyResultUdf($"AMS_PRGRM_ID", $"y_AMS_PRGRM_ID")).drop("AMS_PRGRM_ID").drop("y_AMS_PRGRM_ID")
      .withColumn("c_ADVRTSR_ID", verifyResultUdf($"ADVRTSR_ID", $"y_ADVRTSR_ID")).drop("ADVRTSR_ID").drop("y_ADVRTSR_ID")
      .withColumn("c_AMS_CLICK_FLTR_TYPE_ID", verifyResultUdf($"AMS_CLICK_FLTR_TYPE_ID", $"y_AMS_CLICK_FLTR_TYPE_ID")).drop("AMS_CLICK_FLTR_TYPE_ID").drop("y_AMS_CLICK_FLTR_TYPE_ID")
      .withColumn("c_FILTER_YN_IND", verifyResultUdf($"FILTER_YN_IND", $"y_FILTER_YN_IND")).drop("FILTER_YN_IND").drop("y_FILTER_YN_IND")
      .withColumn("c_MPLX_TIMEOUT_FLAG", verifyResultUdf($"MPLX_TIMEOUT_FLAG", $"y_MPLX_TIMEOUT_FLAG")).drop("MPLX_TIMEOUT_FLAG").drop("y_MPLX_TIMEOUT_FLAG")
      .withColumn("c_CB_KW", verifyResultUdf($"CB_KW", $"y_CB_KW")).drop("CB_KW").drop("y_CB_KW")
      .withColumn("c_CB_CAT", verifyResultUdf($"CB_CAT", $"y_CB_CAT")).drop("CB_CAT").drop("y_CB_CAT")
      .withColumn("c_CB_EX_KW", verifyClick_TSResultUdf($"CB_EX_KW", $"y_CB_EX_KW")).drop("CB_EX_KW").drop("y_CB_EX_KW")
      .withColumn("c_CB_EX_CAT", verifyResultUdf($"CB_EX_CAT", $"y_CB_EX_CAT")).drop("CB_EX_CAT").drop("y_CB_EX_CAT")
      .withColumn("c_FB_USED", verifyResultUdf($"FB_USED", $"y_FB_USED")).drop("FB_USED").drop("y_FB_USED")
      .withColumn("c_AD_FORMAT", verifyResultUdf($"AD_FORMAT", $"y_AD_FORMAT")).drop("AD_FORMAT").drop("y_AD_FORMAT")
      .withColumn("c_AD_CONTENT_TYPE", verifyResultUdf($"AD_CONTENT_TYPE", $"y_AD_CONTENT_TYPE")).drop("AD_CONTENT_TYPE").drop("y_AD_CONTENT_TYPE")
      .withColumn("c_LOAD_TIME", verifyResultUdf($"LOAD_TIME", $"y_LOAD_TIME")).drop("LOAD_TIME").drop("y_LOAD_TIME")
      .withColumn("c_APP_ID", verifyResultUdf($"APP_ID", $"y_APP_ID")).drop("APP_ID").drop("y_APP_ID")
      .withColumn( "c_APP_PACKAGE_NAME", verifyResultUdf($"APP_PACKAGE_NAME", $"y_APP_PACKAGE_NAME")).drop("APP_PACKAGE_NAME").drop("y_APP_PACKAGE_NAME")
      .withColumn("c_APP_NAME", verifyResultUdf($"APP_NAME", $"y_APP_NAME")).drop("APP_NAME").drop("y_APP_NAME")
      .withColumn("c_APP_VERSION", verifyResultUdf($"APP_VERSION", $"y_APP_VERSION")).drop("APP_VERSION").drop("y_APP_VERSION")
      .withColumn("c_DEVICE_NAME", verifyResultUdf($"DEVICE_NAME", $"y_DEVICE_NAME")).drop("DEVICE_NAME").drop("y_DEVICE_NAME")
      .withColumn("c_OS_NAME", verifyResultUdf($"OS_NAME", $"y_OS_NAME")).drop("OS_NAME").drop("y_OS_NAME")
      .withColumn("c_OS_VERSION", verifyResultUdf($"OS_VERSION", $"y_OS_VERSION")).drop("OS_VERSION").drop("y_OS_VERSION")
      .withColumn("c_UDID", verifyResultUdf($"UDID", $"y_UDID")).drop("UDID").drop("y_UDID")
      .withColumn("c_SDK_NAME", verifyResultUdf($"SDK_NAME", $"y_SDK_NAME")).drop("SDK_NAME").drop("y_SDK_NAME")
      .withColumn("c_SDK_VERSION", verifyResultUdf($"SDK_VERSION", $"y_SDK_VERSION")).drop("SDK_VERSION").drop("y_SDK_VERSION")
      .withColumn("c_AMS_TRANS_RSN_CD", verifyResultUdf($"AMS_TRANS_RSN_CD", $"y_AMS_TRANS_RSN_CD")).drop("AMS_TRANS_RSN_CD").drop("y_AMS_TRANS_RSN_CD")
      .withColumn("c_TRFC_SRC_CD", verifyResultUdf($"TRFC_SRC_CD", $"y_TRFC_SRC_CD")).drop("TRFC_SRC_CD").drop("y_TRFC_SRC_CD")
      .withColumn("c_RT_RULE_FLAG1", verifyResultUdf($"RT_RULE_FLAG1", $"y_RT_RULE_FLAG1")).drop("RT_RULE_FLAG1").drop("y_RT_RULE_FLAG1")
      .withColumn("c_RT_RULE_FLAG2", verifyResultUdf($"RT_RULE_FLAG2", $"y_RT_RULE_FLAG2")).drop("RT_RULE_FLAG2").drop("y_RT_RULE_FLAG2")
      .withColumn("c_RT_RULE_FLAG3", verifyResultUdf($"RT_RULE_FLAG3", $"y_RT_RULE_FLAG3")).drop("RT_RULE_FLAG3").drop("y_RT_RULE_FLAG3")
      .withColumn("c_RT_RULE_FLAG4", verifyResultUdf($"RT_RULE_FLAG4", $"y_RT_RULE_FLAG4")).drop("RT_RULE_FLAG4").drop("y_RT_RULE_FLAG4")
      .withColumn("c_RT_RULE_FLAG5", verifyResultUdf($"RT_RULE_FLAG5", $"y_RT_RULE_FLAG5")).drop("RT_RULE_FLAG5").drop("y_RT_RULE_FLAG5")
      .withColumn("c_RT_RULE_FLAG6", verifyResultUdf($"RT_RULE_FLAG6", $"y_RT_RULE_FLAG6")).drop("RT_RULE_FLAG6").drop("y_RT_RULE_FLAG6")
      .withColumn("c_RT_RULE_FLAG7", verifyResultUdf($"RT_RULE_FLAG7", $"y_RT_RULE_FLAG7")).drop("RT_RULE_FLAG7").drop("y_RT_RULE_FLAG7")
      .withColumn("c_RT_RULE_FLAG8", verifyResultUdf($"RT_RULE_FLAG8", $"y_RT_RULE_FLAG8")).drop("RT_RULE_FLAG8").drop("y_RT_RULE_FLAG8")
      .withColumn("c_RT_RULE_FLAG9", verifyResultUdf($"RT_RULE_FLAG9", $"y_RT_RULE_FLAG9")).drop("RT_RULE_FLAG9").drop("y_RT_RULE_FLAG9")
      .withColumn("c_RT_RULE_FLAG10", verifyResultUdf($"RT_RULE_FLAG10", $"y_RT_RULE_FLAG10")).drop("RT_RULE_FLAG10").drop("y_RT_RULE_FLAG10")
      .withColumn("c_RT_RULE_FLAG11", verifyResultUdf($"RT_RULE_FLAG11", $"y_RT_RULE_FLAG11")).drop("RT_RULE_FLAG11").drop("y_RT_RULE_FLAG11")
      .withColumn("c_RT_RULE_FLAG12", verifyResultUdf($"RT_RULE_FLAG12", $"y_RT_RULE_FLAG12")).drop("RT_RULE_FLAG12").drop("y_RT_RULE_FLAG12")
      .withColumn("c_RT_RULE_FLAG13", verifyResultUdf($"RT_RULE_FLAG13", $"y_RT_RULE_FLAG13")).drop("RT_RULE_FLAG13").drop("y_RT_RULE_FLAG13")
      .withColumn("c_RT_RULE_FLAG14", verifyResultUdf($"RT_RULE_FLAG14", $"y_RT_RULE_FLAG14")).drop("RT_RULE_FLAG14").drop("y_RT_RULE_FLAG14")
      .withColumn("c_RT_RULE_FLAG15", verifyResultUdf($"RT_RULE_FLAG15", $"y_RT_RULE_FLAG15")).drop("RT_RULE_FLAG15").drop("y_RT_RULE_FLAG15")
      .withColumn("c_RT_RULE_FLAG16", verifyResultUdf($"RT_RULE_FLAG16", $"y_RT_RULE_FLAG16")).drop("RT_RULE_FLAG16").drop("y_RT_RULE_FLAG16")
      .withColumn("c_RT_RULE_FLAG17", verifyResultUdf($"RT_RULE_FLAG17", $"y_RT_RULE_FLAG17")).drop("RT_RULE_FLAG17").drop("y_RT_RULE_FLAG17")
      .withColumn("c_RT_RULE_FLAG18", verifyResultUdf($"RT_RULE_FLAG18", $"y_RT_RULE_FLAG18")).drop("RT_RULE_FLAG18").drop("y_RT_RULE_FLAG18")
      .withColumn("c_RT_RULE_FLAG19", verifyResultUdf($"RT_RULE_FLAG19", $"y_RT_RULE_FLAG19")).drop("RT_RULE_FLAG19").drop("y_RT_RULE_FLAG19")
      .withColumn("c_RT_RULE_FLAG20", verifyResultUdf($"RT_RULE_FLAG20", $"y_RT_RULE_FLAG20")).drop("RT_RULE_FLAG20").drop("y_RT_RULE_FLAG20")
      .withColumn("c_RT_RULE_FLAG21", verifyResultUdf($"RT_RULE_FLAG21", $"y_RT_RULE_FLAG21")).drop("RT_RULE_FLAG21").drop("y_RT_RULE_FLAG21")
      .withColumn("c_RT_RULE_FLAG22", verifyResultUdf($"RT_RULE_FLAG22", $"y_RT_RULE_FLAG22")).drop("RT_RULE_FLAG22").drop("y_RT_RULE_FLAG22")
      .withColumn("c_RT_RULE_FLAG23", verifyResultUdf($"RT_RULE_FLAG23", $"y_RT_RULE_FLAG23")).drop("RT_RULE_FLAG23").drop("y_RT_RULE_FLAG23")
      .withColumn("c_RT_RULE_FLAG24", verifyResultUdf($"RT_RULE_FLAG24", $"y_RT_RULE_FLAG24")).drop("RT_RULE_FLAG24").drop("y_RT_RULE_FLAG24")
      .withColumn("c_NRT_RULE_FLAG1", verifyResultUdf($"NRT_RULE_FLAG1", $"y_NRT_RULE_FLAG1")).drop("NRT_RULE_FLAG1").drop("y_NRT_RULE_FLAG1")
      .withColumn("c_NRT_RULE_FLAG2", verifyResultUdf($"NRT_RULE_FLAG2", $"y_NRT_RULE_FLAG2")).drop("NRT_RULE_FLAG2").drop("y_NRT_RULE_FLAG2")
      .withColumn("c_NRT_RULE_FLAG3", verifyResultUdf($"NRT_RULE_FLAG3", $"y_NRT_RULE_FLAG3")).drop("NRT_RULE_FLAG3").drop("y_NRT_RULE_FLAG3")
      .withColumn("c_NRT_RULE_FLAG4", verifyResultUdf($"NRT_RULE_FLAG4", $"y_NRT_RULE_FLAG4")).drop("NRT_RULE_FLAG4").drop("y_NRT_RULE_FLAG4")
      .withColumn("c_NRT_RULE_FLAG5", verifyResultUdf($"NRT_RULE_FLAG5", $"y_NRT_RULE_FLAG5")).drop("NRT_RULE_FLAG5").drop("y_NRT_RULE_FLAG5")
      .withColumn("c_NRT_RULE_FLAG6", verifyResultUdf($"NRT_RULE_FLAG6", $"y_NRT_RULE_FLAG6")).drop("NRT_RULE_FLAG6").drop("y_NRT_RULE_FLAG6")
      .withColumn("c_NRT_RULE_FLAG7", verifyResultUdf($"NRT_RULE_FLAG7", $"y_NRT_RULE_FLAG7")).drop("NRT_RULE_FLAG7").drop("y_NRT_RULE_FLAG7")
      .withColumn("c_NRT_RULE_FLAG8", verifyResultUdf($"NRT_RULE_FLAG8", $"y_NRT_RULE_FLAG8")).drop("NRT_RULE_FLAG8").drop("y_NRT_RULE_FLAG8")
      .withColumn("c_NRT_RULE_FLAG9", verifyResultUdf($"NRT_RULE_FLAG9", $"y_NRT_RULE_FLAG9")).drop("NRT_RULE_FLAG9").drop("y_NRT_RULE_FLAG9")
      .withColumn("c_NRT_RULE_FLAG10", verifyResultUdf($"NRT_RULE_FLAG10", $"y_NRT_RULE_FLAG10")).drop("NRT_RULE_FLAG10").drop("y_NRT_RULE_FLAG10")
      .withColumn("c_NRT_RULE_FLAG11", verifyResultUdf($"NRT_RULE_FLAG11", $"y_NRT_RULE_FLAG11")).drop("NRT_RULE_FLAG11").drop("y_NRT_RULE_FLAG11")
      .withColumn("c_NRT_RULE_FLAG12", verifyResultUdf($"NRT_RULE_FLAG12", $"y_NRT_RULE_FLAG12")).drop("NRT_RULE_FLAG12").drop("y_NRT_RULE_FLAG12")
      .withColumn("c_NRT_RULE_FLAG13", verifyResultUdf($"NRT_RULE_FLAG13", $"y_NRT_RULE_FLAG13")).drop("NRT_RULE_FLAG13").drop("y_NRT_RULE_FLAG13")
      .withColumn("c_NRT_RULE_FLAG14", verifyResultUdf($"NRT_RULE_FLAG14", $"y_NRT_RULE_FLAG14")).drop("NRT_RULE_FLAG14").drop("y_NRT_RULE_FLAG14")
      .withColumn("c_NRT_RULE_FLAG15", verifyResultUdf($"NRT_RULE_FLAG15", $"y_NRT_RULE_FLAG15")).drop("NRT_RULE_FLAG15").drop("y_NRT_RULE_FLAG15")
      .withColumn("c_NRT_RULE_FLAG16", verifyResultUdf($"NRT_RULE_FLAG16", $"y_NRT_RULE_FLAG16")).drop("NRT_RULE_FLAG16").drop("y_NRT_RULE_FLAG16")
      .withColumn("c_NRT_RULE_FLAG17", verifyResultUdf($"NRT_RULE_FLAG17", $"y_NRT_RULE_FLAG17")).drop("NRT_RULE_FLAG17").drop("y_NRT_RULE_FLAG17")
      .withColumn("c_NRT_RULE_FLAG18", verifyResultUdf($"NRT_RULE_FLAG18", $"y_NRT_RULE_FLAG18")).drop("NRT_RULE_FLAG18").drop("y_NRT_RULE_FLAG18")
      .withColumn("c_NRT_RULE_FLAG19", verifyResultUdf($"NRT_RULE_FLAG19", $"y_NRT_RULE_FLAG19")).drop("NRT_RULE_FLAG19").drop("y_NRT_RULE_FLAG19")
      .withColumn("c_NRT_RULE_FLAG20", verifyResultUdf($"NRT_RULE_FLAG20", $"y_NRT_RULE_FLAG20")).drop("NRT_RULE_FLAG20").drop("y_NRT_RULE_FLAG20")
      .withColumn("c_NRT_RULE_FLAG21", verifyResultUdf($"NRT_RULE_FLAG21", $"y_NRT_RULE_FLAG21")).drop("NRT_RULE_FLAG21").drop("y_NRT_RULE_FLAG21")
      .withColumn("c_NRT_RULE_FLAG22", verifyResultUdf($"NRT_RULE_FLAG22", $"y_NRT_RULE_FLAG22")).drop("NRT_RULE_FLAG22").drop("y_NRT_RULE_FLAG22")
      .withColumn("c_NRT_RULE_FLAG23", verifyResultUdf($"NRT_RULE_FLAG23", $"y_NRT_RULE_FLAG23")).drop("NRT_RULE_FLAG23").drop("y_NRT_RULE_FLAG23")
      .withColumn("c_NRT_RULE_FLAG24", verifyResultUdf($"NRT_RULE_FLAG24", $"y_NRT_RULE_FLAG24")).drop("NRT_RULE_FLAG24").drop("y_NRT_RULE_FLAG24")
      .withColumn("c_NRT_RULE_FLAG25", verifyResultUdf($"NRT_RULE_FLAG25", $"y_NRT_RULE_FLAG25")).drop("NRT_RULE_FLAG25").drop("y_NRT_RULE_FLAG25")
      .withColumn("c_NRT_RULE_FLAG26", verifyResultUdf($"NRT_RULE_FLAG26", $"y_NRT_RULE_FLAG26")).drop("NRT_RULE_FLAG26").drop("y_NRT_RULE_FLAG26")
      .withColumn("c_NRT_RULE_FLAG27", verifyResultUdf($"NRT_RULE_FLAG27", $"y_NRT_RULE_FLAG27")).drop("NRT_RULE_FLAG27").drop("y_NRT_RULE_FLAG27")
      .withColumn("c_NRT_RULE_FLAG28", verifyResultUdf($"NRT_RULE_FLAG28", $"y_NRT_RULE_FLAG28")).drop("NRT_RULE_FLAG28").drop("y_NRT_RULE_FLAG28")
      .withColumn("c_NRT_RULE_FLAG29", verifyResultUdf($"NRT_RULE_FLAG29", $"y_NRT_RULE_FLAG29")).drop("NRT_RULE_FLAG29").drop("y_NRT_RULE_FLAG29")
      .withColumn("c_NRT_RULE_FLAG30", verifyResultUdf($"NRT_RULE_FLAG30", $"y_NRT_RULE_FLAG30")).drop("NRT_RULE_FLAG30").drop("y_NRT_RULE_FLAG30")
      .withColumn("c_NRT_RULE_FLAG31", verifyResultUdf($"NRT_RULE_FLAG31", $"y_NRT_RULE_FLAG31")).drop("NRT_RULE_FLAG31").drop("y_NRT_RULE_FLAG31")
      .withColumn("c_NRT_RULE_FLAG32", verifyResultUdf($"NRT_RULE_FLAG32", $"y_NRT_RULE_FLAG32")).drop("NRT_RULE_FLAG32").drop("y_NRT_RULE_FLAG32")
      .withColumn("c_NRT_RULE_FLAG33", verifyResultUdf($"NRT_RULE_FLAG33", $"y_NRT_RULE_FLAG33")).drop("NRT_RULE_FLAG33").drop("y_NRT_RULE_FLAG33")
      .withColumn("c_NRT_RULE_FLAG34", verifyResultUdf($"NRT_RULE_FLAG34", $"y_NRT_RULE_FLAG34")).drop("NRT_RULE_FLAG34").drop("y_NRT_RULE_FLAG34")
      .withColumn("c_NRT_RULE_FLAG35", verifyResultUdf($"NRT_RULE_FLAG35", $"y_NRT_RULE_FLAG35")).drop("NRT_RULE_FLAG35").drop("y_NRT_RULE_FLAG35")
      .withColumn("c_NRT_RULE_FLAG36", verifyResultUdf($"NRT_RULE_FLAG36", $"y_NRT_RULE_FLAG36")).drop("NRT_RULE_FLAG36").drop("y_NRT_RULE_FLAG36")
      .withColumn("c_NRT_RULE_FLAG37", verifyResultUdf($"NRT_RULE_FLAG37", $"y_NRT_RULE_FLAG37")).drop("NRT_RULE_FLAG37").drop("y_NRT_RULE_FLAG37")
      .withColumn("c_NRT_RULE_FLAG38", verifyResultUdf($"NRT_RULE_FLAG38", $"y_NRT_RULE_FLAG38")).drop("NRT_RULE_FLAG38").drop("y_NRT_RULE_FLAG38")
      .withColumn("c_NRT_RULE_FLAG39", verifyResultUdf($"NRT_RULE_FLAG39", $"y_NRT_RULE_FLAG39")).drop("NRT_RULE_FLAG39").drop("y_NRT_RULE_FLAG39")
      .withColumn("c_NRT_RULE_FLAG40", verifyResultUdf($"NRT_RULE_FLAG40", $"y_NRT_RULE_FLAG40")).drop("NRT_RULE_FLAG40").drop("y_NRT_RULE_FLAG40")
      .withColumn("c_NRT_RULE_FLAG41", verifyResultUdf($"NRT_RULE_FLAG41", $"y_NRT_RULE_FLAG41")).drop("NRT_RULE_FLAG41").drop("y_NRT_RULE_FLAG41")
      .withColumn("c_NRT_RULE_FLAG42", verifyResultUdf($"NRT_RULE_FLAG42", $"y_NRT_RULE_FLAG42")).drop("NRT_RULE_FLAG42").drop("y_NRT_RULE_FLAG42")
      .withColumn("c_NRT_RULE_FLAG43", verifyResultUdf($"NRT_RULE_FLAG43", $"y_NRT_RULE_FLAG43")).drop("NRT_RULE_FLAG43").drop("y_NRT_RULE_FLAG43")
      .withColumn("c_NRT_RULE_FLAG44", verifyResultUdf($"NRT_RULE_FLAG44", $"y_NRT_RULE_FLAG44")).drop("NRT_RULE_FLAG44").drop("y_NRT_RULE_FLAG44")
      .withColumn("c_NRT_RULE_FLAG45", verifyResultUdf($"NRT_RULE_FLAG45", $"y_NRT_RULE_FLAG45")).drop("NRT_RULE_FLAG45").drop("y_NRT_RULE_FLAG45")
      .withColumn("c_NRT_RULE_FLAG46", verifyResultUdf($"NRT_RULE_FLAG46", $"y_NRT_RULE_FLAG46")).drop("NRT_RULE_FLAG46").drop("y_NRT_RULE_FLAG46")
      .withColumn("c_NRT_RULE_FLAG47", verifyResultUdf($"NRT_RULE_FLAG47", $"y_NRT_RULE_FLAG47")).drop("NRT_RULE_FLAG47").drop("y_NRT_RULE_FLAG47")
      .withColumn("c_NRT_RULE_FLAG48", verifyResultUdf($"NRT_RULE_FLAG48", $"y_NRT_RULE_FLAG48")).drop("NRT_RULE_FLAG48").drop("y_NRT_RULE_FLAG48")
      .withColumn("c_NRT_RULE_FLAG49", verifyResultUdf($"NRT_RULE_FLAG49", $"y_NRT_RULE_FLAG49")).drop("NRT_RULE_FLAG49").drop("y_NRT_RULE_FLAG49")
      .withColumn("c_NRT_RULE_FLAG50", verifyResultUdf($"NRT_RULE_FLAG50", $"y_NRT_RULE_FLAG50")).drop("NRT_RULE_FLAG50").drop("y_NRT_RULE_FLAG50")
      .withColumn("c_NRT_RULE_FLAG51", verifyResultUdf($"NRT_RULE_FLAG51", $"y_NRT_RULE_FLAG51")).drop("NRT_RULE_FLAG51").drop("y_NRT_RULE_FLAG51")
      .withColumn("c_NRT_RULE_FLAG52", verifyResultUdf($"NRT_RULE_FLAG52", $"y_NRT_RULE_FLAG52")).drop("NRT_RULE_FLAG52").drop("y_NRT_RULE_FLAG52")
      .withColumn("c_NRT_RULE_FLAG53", verifyResultUdf($"NRT_RULE_FLAG53", $"y_NRT_RULE_FLAG53")).drop("NRT_RULE_FLAG53").drop("y_NRT_RULE_FLAG53")
      .withColumn("c_NRT_RULE_FLAG54", verifyResultUdf($"NRT_RULE_FLAG54", $"y_NRT_RULE_FLAG54")).drop("NRT_RULE_FLAG54").drop("y_NRT_RULE_FLAG54")
      .withColumn("c_NRT_RULE_FLAG55", verifyResultUdf($"NRT_RULE_FLAG55", $"y_NRT_RULE_FLAG55")).drop("NRT_RULE_FLAG55").drop("y_NRT_RULE_FLAG55")
      .withColumn("c_NRT_RULE_FLAG56", verifyResultUdf($"NRT_RULE_FLAG56", $"y_NRT_RULE_FLAG56")).drop("NRT_RULE_FLAG56").drop("y_NRT_RULE_FLAG56")
      .withColumn("c_NRT_RULE_FLAG57", verifyResultUdf($"NRT_RULE_FLAG57", $"y_NRT_RULE_FLAG57")).drop("NRT_RULE_FLAG57").drop("y_NRT_RULE_FLAG57")
      .withColumn("c_NRT_RULE_FLAG58", verifyResultUdf($"NRT_RULE_FLAG58", $"y_NRT_RULE_FLAG58")).drop("NRT_RULE_FLAG58").drop("y_NRT_RULE_FLAG58")
      .withColumn("c_NRT_RULE_FLAG59", verifyResultUdf($"NRT_RULE_FLAG59", $"y_NRT_RULE_FLAG59")).drop("NRT_RULE_FLAG59").drop("y_NRT_RULE_FLAG59")
      .withColumn("c_NRT_RULE_FLAG60", verifyResultUdf($"NRT_RULE_FLAG60", $"y_NRT_RULE_FLAG60")).drop("NRT_RULE_FLAG60").drop("y_NRT_RULE_FLAG60")
      .withColumn("c_NRT_RULE_FLAG61", verifyResultUdf($"NRT_RULE_FLAG61", $"y_NRT_RULE_FLAG61")).drop("NRT_RULE_FLAG61").drop("y_NRT_RULE_FLAG61")
      .withColumn("c_NRT_RULE_FLAG62", verifyResultUdf($"NRT_RULE_FLAG62", $"y_NRT_RULE_FLAG62")).drop("NRT_RULE_FLAG62").drop("y_NRT_RULE_FLAG62")
      .withColumn("c_NRT_RULE_FLAG63", verifyResultUdf($"NRT_RULE_FLAG63", $"y_NRT_RULE_FLAG63")).drop("NRT_RULE_FLAG63").drop("y_NRT_RULE_FLAG63")
      .withColumn("c_NRT_RULE_FLAG64", verifyResultUdf($"NRT_RULE_FLAG64", $"y_NRT_RULE_FLAG64")).drop("NRT_RULE_FLAG64").drop("y_NRT_RULE_FLAG64")
      .withColumn("c_NRT_RULE_FLAG65", verifyResultUdf($"NRT_RULE_FLAG65", $"y_NRT_RULE_FLAG65")).drop("NRT_RULE_FLAG65").drop("y_NRT_RULE_FLAG65")
      .withColumn("c_NRT_RULE_FLAG66", verifyResultUdf($"NRT_RULE_FLAG66", $"y_NRT_RULE_FLAG66")).drop("NRT_RULE_FLAG66").drop("y_NRT_RULE_FLAG66")
      .withColumn("c_NRT_RULE_FLAG67", verifyResultUdf($"NRT_RULE_FLAG67", $"y_NRT_RULE_FLAG67")).drop("NRT_RULE_FLAG67").drop("y_NRT_RULE_FLAG67")
      .withColumn("c_NRT_RULE_FLAG68", verifyResultUdf($"NRT_RULE_FLAG68", $"y_NRT_RULE_FLAG68")).drop("NRT_RULE_FLAG68").drop("y_NRT_RULE_FLAG68")
      .withColumn("c_NRT_RULE_FLAG69", verifyResultUdf($"NRT_RULE_FLAG69", $"y_NRT_RULE_FLAG69")).drop("NRT_RULE_FLAG69").drop("y_NRT_RULE_FLAG69")
      .withColumn("c_NRT_RULE_FLAG70", verifyResultUdf($"NRT_RULE_FLAG70", $"y_NRT_RULE_FLAG70")).drop("NRT_RULE_FLAG70").drop("y_NRT_RULE_FLAG70")
      .withColumn("c_NRT_RULE_FLAG71", verifyResultUdf($"NRT_RULE_FLAG71", $"y_NRT_RULE_FLAG71")).drop("NRT_RULE_FLAG71").drop("y_NRT_RULE_FLAG71")
      .withColumn("c_NRT_RULE_FLAG72", verifyResultUdf($"NRT_RULE_FLAG72", $"y_NRT_RULE_FLAG72")).drop("NRT_RULE_FLAG72").drop("y_NRT_RULE_FLAG72")

    val path = new Path(params.workDir, new Path(params.impression_outputPath).getName)
    fs.delete(path, true)
    saveDFToFiles(df, path.toString)
    df = readFilesAsDF(path.toString)
    val total = df.count()

    val IMPRSN_CNTNR_ID = df.where($"c_IMPRSN_CNTNR_ID" === false).count()
    val FILE_SCHM_VRSN_NUM = df.where($"c_FILE_SCHM_VRSN_NUM" === false).count()
    val FILE_ID = df.where($"c_FILE_ID" === false).count()
    val BATCH_ID = df.where($"c_BATCH_ID" === false).count()
    val CHNL_ID = df.where($"c_CHNL_ID" === false).count()
    val GUID_TXT = df.where($"c_GUID_TXT" === false).count()
    val USER_ID = df.where($"c_USER_ID" === false).count()
    val CLNT_RMT_IP = df.where($"c_CLNT_RMT_IP" === false).count()
    val BRWSR_TYPE_NUM = df.where($"c_BRWSR_TYPE_NUM" === false).count()
    val BRWSR_NAME = df.where($"c_BRWSR_NAME" === false).count()
    val RFR_URL_NAME = df.where($"c_RFR_URL_NAME" === false).count()
    val PRVS_RFR_DMN_NAME = df.where($"c_PRVS_RFR_DMN_NAME" === false).count()
    val USER_QUERY_TXT = df.where($"c_USER_QUERY_TXT" === false).count()
    val PLCMNT_DATA_TXT = df.where($"c_PLCMNT_DATA_TXT" === false).count()
    val PBLSHR_ID = df.where($"c_PBLSHR_ID" === false).count()
    val AMS_PBLSHR_CMPGN_ID = df.where($"c_AMS_PBLSHR_CMPGN_ID" === false).count()
    val AMS_TOOL_ID = df.where($"c_AMS_TOOL_ID" === false).count()
    val CSTM_ID = df.where($"c_CSTM_ID" === false).count()
    val FLEX_FLD_VRSN_NUM	= df.where($"c_FLEX_FLD_VRSN_NUM" === false).count()
    val FLEX_FLD_1_TXT = df.where($"c_FLEX_FLD_1_TXT" === false).count()
    val FLEX_FLD_2_TXT = df.where($"c_FLEX_FLD_2_TXT" === false).count()
    val FLEX_FLD_3_TXT = df.where($"c_FLEX_FLD_3_TXT" === false).count()
    val FLEX_FLD_4_TXT = df.where($"c_FLEX_FLD_4_TXT" === false).count()
    val FLEX_FLD_5_TXT = df.where($"c_FLEX_FLD_5_TXT" === false).count()
    val FLEX_FLD_6_TXT = df.where($"c_FLEX_FLD_6_TXT" === false).count()
    val FLEX_FLD_7_TXT = df.where($"c_FLEX_FLD_7_TXT" === false).count()
    val FLEX_FLD_8_TXT = df.where($"c_FLEX_FLD_8_TXT" === false).count()
    val FLEX_FLD_9_TXT = df.where($"c_FLEX_FLD_9_TXT" === false).count()
    val FLEX_FLD_10_TXT = df.where($"c_FLEX_FLD_10_TXT" === false).count()
    val FLEX_FLD_11_TXT = df.where($"c_FLEX_FLD_11_TXT" === false).count()
    val FLEX_FLD_12_TXT = df.where($"c_FLEX_FLD_12_TXT" === false).count()
    val FLEX_FLD_13_TXT = df.where($"c_FLEX_FLD_13_TXT" === false).count()
    val FLEX_FLD_14_TXT = df.where($"c_FLEX_FLD_14_TXT" === false).count()
    val FLEX_FLD_15_TXT = df.where($"c_FLEX_FLD_15_TXT" === false).count()
    val FLEX_FLD_16_TXT = df.where($"c_FLEX_FLD_16_TXT" === false).count()
    val FLEX_FLD_17_TXT = df.where($"c_FLEX_FLD_17_TXT" === false).count()
    val FLEX_FLD_18_TXT = df.where($"c_FLEX_FLD_18_TXT" === false).count()
    val FLEX_FLD_19_TXT = df.where($"c_FLEX_FLD_19_TXT" === false).count()
    val FLEX_FLD_20_TXT = df.where($"c_FLEX_FLD_20_TXT" === false).count()
    val CTX_TXT = df.where($"c_CTX_TXT" === false).count()
    val CTX_CLD_TXT = df.where($"c_CTX_CLD_TXT" === false).count()
    val CTX_RSLT_TXT = df.where($"c_CTX_RSLT_TXT" === false).count()
    val RFR_DMN_NAME = df.where($"c_RFR_DMN_NAME" === false).count()
    val IMPRSN_TS = df.where($"c_IMPRSN_TS" === false).count()
    val AMS_PRGRM_ID = df.where($"c_AMS_PRGRM_ID" === false).count()
    val ADVRTSR_ID = df.where($"c_ADVRTSR_ID" === false).count()
    val AMS_CLICK_FLTR_TYPE_ID = df.where($"c_AMS_CLICK_FLTR_TYPE_ID" === false).count()
    val FILTER_YN_IND = df.where($"c_FILTER_YN_IND" === false).count()
    val MPLX_TIMEOUT_FLAG = df.where($"c_MPLX_TIMEOUT_FLAG" === false).count()
    val CB_KW = df.where($"c_CB_KW" === false).count()
    val CB_CAT = df.where($"c_CB_CAT" === false).count()
    val CB_EX_KW = df.where($"c_CB_EX_KW" === false).count()
    val CB_EX_CAT = df.where($"c_CB_EX_CAT" === false).count()
    val FB_USED = df.where($"c_FB_USED" === false).count()
    val AD_FORMAT = df.where($"c_AD_FORMAT" === false).count()
    val AD_CONTENT_TYPE = df.where($"c_AD_CONTENT_TYPE" === false).count()
    val LOAD_TIME = df.where($"c_LOAD_TIME" === false).count()
    val APP_ID = df.where($"c_APP_ID" === false).count()
    val APP_PACKAGE_NAME = df.where($"c_APP_PACKAGE_NAME" === false).count()
    val APP_NAME = df.where($"c_APP_NAME" === false).count()
    val APP_VERSION = df.where($"c_APP_VERSION" === false).count()
    val DEVICE_NAME = df.where($"c_DEVICE_NAME" === false).count()
    val OS_NAME = df.where($"c_OS_NAME" === false).count()
    val OS_VERSION = df.where($"c_OS_VERSION" === false).count()
    val UDID = df.where($"c_UDID" === false).count()
    val SDK_NAME = df.where($"c_SDK_NAME" === false).count()
    val SDK_VERSION = df.where($"c_SDK_VERSION" === false).count()
    val AMS_TRANS_RSN_CD = df.where($"c_AMS_TRANS_RSN_CD" === false).count()
    val TRFC_SRC_CD = df.where($"c_TRFC_SRC_CD" === false).count()
    val RT_RULE_FLAG1 = df.where($"c_RT_RULE_FLAG1" === false).count()
    val RT_RULE_FLAG2 = df.where($"c_RT_RULE_FLAG2" === false).count()
    val RT_RULE_FLAG3 = df.where($"c_RT_RULE_FLAG3" === false).count()
    val RT_RULE_FLAG4 = df.where($"c_RT_RULE_FLAG4" === false).count()
    val RT_RULE_FLAG5 = df.where($"c_RT_RULE_FLAG5" === false).count()
    val RT_RULE_FLAG6 = df.where($"c_RT_RULE_FLAG6" === false).count()
    val RT_RULE_FLAG7 = df.where($"c_RT_RULE_FLAG7" === false).count()
    val RT_RULE_FLAG8 = df.where($"c_RT_RULE_FLAG8" === false).count()
    val RT_RULE_FLAG9 = df.where($"c_RT_RULE_FLAG9" === false).count()
    val RT_RULE_FLAG10 = df.where($"c_RT_RULE_FLAG10" === false).count()
    val RT_RULE_FLAG11 = df.where($"c_RT_RULE_FLAG11" === false).count()
    val RT_RULE_FLAG12 = df.where($"c_RT_RULE_FLAG12" === false).count()
    val RT_RULE_FLAG13 = df.where($"c_RT_RULE_FLAG13" === false).count()
    val RT_RULE_FLAG14 = df.where($"c_RT_RULE_FLAG14" === false).count()
    val RT_RULE_FLAG15 = df.where($"c_RT_RULE_FLAG15" === false).count()
    val RT_RULE_FLAG16 = df.where($"c_RT_RULE_FLAG16" === false).count()
    val RT_RULE_FLAG17 = df.where($"c_RT_RULE_FLAG17" === false).count()
    val RT_RULE_FLAG18 = df.where($"c_RT_RULE_FLAG18" === false).count()
    val RT_RULE_FLAG19 = df.where($"c_RT_RULE_FLAG19" === false).count()
    val RT_RULE_FLAG20 = df.where($"c_RT_RULE_FLAG20" === false).count()
    val RT_RULE_FLAG21 = df.where($"c_RT_RULE_FLAG21" === false).count()
    val RT_RULE_FLAG22 = df.where($"c_RT_RULE_FLAG22" === false).count()
    val RT_RULE_FLAG23 = df.where($"c_RT_RULE_FLAG23" === false).count()
    val RT_RULE_FLAG24 = df.where($"c_RT_RULE_FLAG24" === false).count()

    val NRT_RULE_FLAG1 = df.where($"c_NRT_RULE_FLAG1" === false).count()
    val NRT_RULE_FLAG2 = df.where($"c_NRT_RULE_FLAG2" === false).count()
    val NRT_RULE_FLAG3 = df.where($"c_NRT_RULE_FLAG3" === false).count()
    val NRT_RULE_FLAG4 = df.where($"c_NRT_RULE_FLAG4" === false).count()
    val NRT_RULE_FLAG5 = df.where($"c_NRT_RULE_FLAG5" === false).count()
    val NRT_RULE_FLAG6 = df.where($"c_NRT_RULE_FLAG6" === false).count()
    val NRT_RULE_FLAG7 = df.where($"c_NRT_RULE_FLAG7" === false).count()
    val NRT_RULE_FLAG8 = df.where($"c_NRT_RULE_FLAG8" === false).count()
    val NRT_RULE_FLAG9 = df.where($"c_NRT_RULE_FLAG9" === false).count()
    val NRT_RULE_FLAG10 = df.where($"c_NRT_RULE_FLAG10" === false).count()
    val NRT_RULE_FLAG11 = df.where($"c_NRT_RULE_FLAG11" === false).count()
    val NRT_RULE_FLAG12 = df.where($"c_NRT_RULE_FLAG12" === false).count()
    val NRT_RULE_FLAG13 = df.where($"c_NRT_RULE_FLAG13" === false).count()
    val NRT_RULE_FLAG14 = df.where($"c_NRT_RULE_FLAG14" === false).count()
    val NRT_RULE_FLAG15 = df.where($"c_NRT_RULE_FLAG15" === false).count()
    val NRT_RULE_FLAG16 = df.where($"c_NRT_RULE_FLAG16" === false).count()
    val NRT_RULE_FLAG17 = df.where($"c_NRT_RULE_FLAG17" === false).count()
    val NRT_RULE_FLAG18 = df.where($"c_NRT_RULE_FLAG18" === false).count()
    val NRT_RULE_FLAG19 = df.where($"c_NRT_RULE_FLAG19" === false).count()
    val NRT_RULE_FLAG20 = df.where($"c_NRT_RULE_FLAG20" === false).count()
    val NRT_RULE_FLAG21 = df.where($"c_NRT_RULE_FLAG21" === false).count()
    val NRT_RULE_FLAG22 = df.where($"c_NRT_RULE_FLAG22" === false).count()
    val NRT_RULE_FLAG23 = df.where($"c_NRT_RULE_FLAG23" === false).count()
    val NRT_RULE_FLAG24 = df.where($"c_NRT_RULE_FLAG24" === false).count()
    val NRT_RULE_FLAG25 = df.where($"c_NRT_RULE_FLAG25" === false).count()
    val NRT_RULE_FLAG26 = df.where($"c_NRT_RULE_FLAG26" === false).count()
    val NRT_RULE_FLAG27 = df.where($"c_NRT_RULE_FLAG27" === false).count()
    val NRT_RULE_FLAG28 = df.where($"c_NRT_RULE_FLAG28" === false).count()
    val NRT_RULE_FLAG29 = df.where($"c_NRT_RULE_FLAG29" === false).count()
    val NRT_RULE_FLAG30 = df.where($"c_NRT_RULE_FLAG30" === false).count()
    val NRT_RULE_FLAG31 = df.where($"c_NRT_RULE_FLAG31" === false).count()
    val NRT_RULE_FLAG32 = df.where($"c_NRT_RULE_FLAG32" === false).count()
    val NRT_RULE_FLAG33 = df.where($"c_NRT_RULE_FLAG33" === false).count()
    val NRT_RULE_FLAG34 = df.where($"c_NRT_RULE_FLAG34" === false).count()
    val NRT_RULE_FLAG35 = df.where($"c_NRT_RULE_FLAG35" === false).count()
    val NRT_RULE_FLAG36 = df.where($"c_NRT_RULE_FLAG36" === false).count()
    val NRT_RULE_FLAG37 = df.where($"c_NRT_RULE_FLAG37" === false).count()
    val NRT_RULE_FLAG38 = df.where($"c_NRT_RULE_FLAG38" === false).count()
    val NRT_RULE_FLAG39 = df.where($"c_NRT_RULE_FLAG39" === false).count()
    val NRT_RULE_FLAG40 = df.where($"c_NRT_RULE_FLAG40" === false).count()
    val NRT_RULE_FLAG41 = df.where($"c_NRT_RULE_FLAG41" === false).count()
    val NRT_RULE_FLAG42 = df.where($"c_NRT_RULE_FLAG42" === false).count()
    val NRT_RULE_FLAG43 = df.where($"c_NRT_RULE_FLAG43" === false).count()
    val NRT_RULE_FLAG44 = df.where($"c_NRT_RULE_FLAG44" === false).count()
    val NRT_RULE_FLAG45 = df.where($"c_NRT_RULE_FLAG45" === false).count()
    val NRT_RULE_FLAG46 = df.where($"c_NRT_RULE_FLAG46" === false).count()
    val NRT_RULE_FLAG47 = df.where($"c_NRT_RULE_FLAG47" === false).count()
    val NRT_RULE_FLAG48 = df.where($"c_NRT_RULE_FLAG48" === false).count()
    val NRT_RULE_FLAG49 = df.where($"c_NRT_RULE_FLAG49" === false).count()
    val NRT_RULE_FLAG50 = df.where($"c_NRT_RULE_FLAG50" === false).count()
    val NRT_RULE_FLAG51 = df.where($"c_NRT_RULE_FLAG51" === false).count()
    val NRT_RULE_FLAG52 = df.where($"c_NRT_RULE_FLAG52" === false).count()
    val NRT_RULE_FLAG53 = df.where($"c_NRT_RULE_FLAG53" === false).count()
    val NRT_RULE_FLAG54 = df.where($"c_NRT_RULE_FLAG54" === false).count()
    val NRT_RULE_FLAG55 = df.where($"c_NRT_RULE_FLAG55" === false).count()
    val NRT_RULE_FLAG56 = df.where($"c_NRT_RULE_FLAG56" === false).count()
    val NRT_RULE_FLAG57 = df.where($"c_NRT_RULE_FLAG57" === false).count()
    val NRT_RULE_FLAG58 = df.where($"c_NRT_RULE_FLAG58" === false).count()
    val NRT_RULE_FLAG59 = df.where($"c_NRT_RULE_FLAG59" === false).count()
    val NRT_RULE_FLAG60 = df.where($"c_NRT_RULE_FLAG60" === false).count()
    val NRT_RULE_FLAG61 = df.where($"c_NRT_RULE_FLAG61" === false).count()
    val NRT_RULE_FLAG62 = df.where($"c_NRT_RULE_FLAG62" === false).count()
    val NRT_RULE_FLAG63 = df.where($"c_NRT_RULE_FLAG63" === false).count()
    val NRT_RULE_FLAG64 = df.where($"c_NRT_RULE_FLAG64" === false).count()
    val NRT_RULE_FLAG65 = df.where($"c_NRT_RULE_FLAG65" === false).count()
    val NRT_RULE_FLAG66 = df.where($"c_NRT_RULE_FLAG66" === false).count()
    val NRT_RULE_FLAG67 = df.where($"c_NRT_RULE_FLAG67" === false).count()
    val NRT_RULE_FLAG68 = df.where($"c_NRT_RULE_FLAG68" === false).count()
    val NRT_RULE_FLAG69 = df.where($"c_NRT_RULE_FLAG69" === false).count()
    val NRT_RULE_FLAG70 = df.where($"c_NRT_RULE_FLAG70" === false).count()
    val NRT_RULE_FLAG71 = df.where($"c_NRT_RULE_FLAG71" === false).count()
    val NRT_RULE_FLAG72 = df.where($"c_NRT_RULE_FLAG72" === false).count()

    var outputStream: FSDataOutputStream = null

    val ourCount = ourDf.count()
    val yourCount = yourDf.count()
   // val total = df.count()

    try {
      outputStream = fs.create(new Path(params.impression_outputPath))
      outputStream.writeChars(s"Chocolate Total: $ourCount \n")
      outputStream.writeChars(s"EPN Total: $yourCount \n")
      outputStream.writeChars(s"Join Total: $total \n")
      outputStream.writeChars(s"Chocolate join ratio: ${((total.toFloat/ourCount)*100).toInt}% \n")
      outputStream.writeChars(s"EPN join ratio: ${((total.toFloat/yourCount)*100).toInt}% \n")

      outputStream.writeChars("--------------------------------------------------------" + "\n")
      outputStream.writeChars(s"IMPRSN_CNTNR_ID inconsistent: ${((IMPRSN_CNTNR_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FILE_SCHM_VRSN_NUM inconsistent: ${((FILE_SCHM_VRSN_NUM.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FILE_ID inconsistent: ${((FILE_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"BATCH_ID inconsistent: ${((BATCH_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CHNL_ID inconsistent: ${((CHNL_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"GUID_TXT inconsistent: ${((GUID_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"USER_ID inconsistent: ${((USER_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CLNT_RMT_IP inconsistent: ${((CLNT_RMT_IP.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"BRWSR_TYPE_NUM inconsistent: ${((BRWSR_TYPE_NUM.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"BRWSR_NAME inconsistent: ${((BRWSR_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RFR_URL_NAME inconsistent: ${((RFR_URL_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"PRVS_RFR_DMN_NAME inconsistent: ${((PRVS_RFR_DMN_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"USER_QUERY_TXT inconsistent: ${((USER_QUERY_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"PLCMNT_DATA_TXT inconsistent: ${((PLCMNT_DATA_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"PBLSHR_ID inconsistent: ${((PBLSHR_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AMS_PBLSHR_CMPGN_ID inconsistent: ${((AMS_PBLSHR_CMPGN_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AMS_TOOL_ID inconsistent: ${((AMS_TOOL_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CSTM_ID inconsistent: ${((CSTM_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_VRSN_NUM inconsistent: ${((FLEX_FLD_VRSN_NUM.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_1_TXT inconsistent: ${((FLEX_FLD_1_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_2_TXT inconsistent: ${((FLEX_FLD_2_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_3_TXT inconsistent: ${((FLEX_FLD_3_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_4_TXT inconsistent: ${((FLEX_FLD_4_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_5_TXT inconsistent: ${((FLEX_FLD_5_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_6_TXT inconsistent: ${((FLEX_FLD_6_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_7_TXT inconsistent: ${((FLEX_FLD_7_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_8_TXT inconsistent: ${((FLEX_FLD_8_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_9_TXT inconsistent: ${((FLEX_FLD_9_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_10_TXT inconsistent: ${((FLEX_FLD_10_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_11_TXT inconsistent: ${((FLEX_FLD_11_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_12_TXT inconsistent: ${((FLEX_FLD_12_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_13_TXT inconsistent: ${((FLEX_FLD_13_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_14_TXT inconsistent: ${((FLEX_FLD_14_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_15_TXT inconsistent: ${((FLEX_FLD_15_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_16_TXT inconsistent: ${((FLEX_FLD_16_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_17_TXT inconsistent: ${((FLEX_FLD_17_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_18_TXT inconsistent: ${((FLEX_FLD_18_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_19_TXT inconsistent: ${((FLEX_FLD_19_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FLEX_FLD_20_TXT inconsistent: ${((FLEX_FLD_20_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CTX_TXT inconsistent: ${((CTX_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CTX_CLD_TXT inconsistent: ${((CTX_CLD_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CTX_RSLT_TXT inconsistent: ${((CTX_RSLT_TXT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RFR_DMN_NAME inconsistent: ${((RFR_DMN_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"IMPRSN_TS inconsistent: ${((IMPRSN_TS.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AMS_PRGRM_ID inconsistent: ${((AMS_PRGRM_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"ADVRTSR_ID inconsistent: ${((ADVRTSR_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AMS_CLICK_FLTR_TYPE_ID inconsistent: ${((AMS_CLICK_FLTR_TYPE_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FILTER_YN_IND inconsistent: ${((FILTER_YN_IND.toFloat/total)*100).toInt}% \n")

      outputStream.writeChars(s"MPLX_TIMEOUT_FLAG inconsistent: ${((MPLX_TIMEOUT_FLAG.toFloat/total)*100).toInt}% \n")

      outputStream.writeChars(s"CB_KW inconsistent: ${((CB_KW.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CB_CAT inconsistent: ${((CB_CAT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CB_EX_KW inconsistent: ${((CB_EX_KW.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"CB_EX_CAT inconsistent: ${((CB_EX_CAT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"FB_USED inconsistent: ${((FB_USED.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AD_FORMAT inconsistent: ${((AD_FORMAT.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AD_CONTENT_TYPE inconsistent: ${((AD_CONTENT_TYPE.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"LOAD_TIME inconsistent: ${((LOAD_TIME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"APP_ID inconsistent: ${((APP_ID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"APP_PACKAGE_NAME inconsistent: ${((APP_PACKAGE_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"APP_NAME inconsistent: ${((APP_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"APP_VERSION inconsistent: ${((APP_VERSION.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"DEVICE_NAME inconsistent: ${((DEVICE_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"OS_NAME inconsistent: ${((OS_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"OS_VERSION inconsistent: ${((OS_VERSION.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"UDID inconsistent: ${((UDID.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"SDK_NAME inconsistent: ${((SDK_NAME.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"SDK_VERSION inconsistent: ${((SDK_VERSION.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"AMS_TRANS_RSN_CD inconsistent: ${((AMS_TRANS_RSN_CD.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"TRFC_SRC_CD inconsistent: ${((TRFC_SRC_CD.toFloat/total)*100).toInt}% \n")

      outputStream.writeChars(s"RT_RULE_FLAG1 inconsistent: ${((RT_RULE_FLAG1.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG2 inconsistent: ${((RT_RULE_FLAG2.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG3 inconsistent: ${((RT_RULE_FLAG3.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG4 inconsistent: ${((RT_RULE_FLAG4.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG5 inconsistent: ${((RT_RULE_FLAG5.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG6 inconsistent: ${((RT_RULE_FLAG6.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG7 inconsistent: ${((RT_RULE_FLAG7.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG8 inconsistent: ${((RT_RULE_FLAG8.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG9 inconsistent: ${((RT_RULE_FLAG9.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG10 inconsistent: ${((RT_RULE_FLAG10.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG11 inconsistent: ${((RT_RULE_FLAG11.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG12 inconsistent: ${((RT_RULE_FLAG12.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG13 inconsistent: ${((RT_RULE_FLAG13.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG14 inconsistent: ${((RT_RULE_FLAG14.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG15 inconsistent: ${((RT_RULE_FLAG15.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG16 inconsistent: ${((RT_RULE_FLAG16.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG17 inconsistent: ${((RT_RULE_FLAG17.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG18 inconsistent: ${((RT_RULE_FLAG18.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG19 inconsistent: ${((RT_RULE_FLAG19.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG20 inconsistent: ${((RT_RULE_FLAG20.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG21 inconsistent: ${((RT_RULE_FLAG21.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG22 inconsistent: ${((RT_RULE_FLAG22.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG23 inconsistent: ${((RT_RULE_FLAG23.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"RT_RULE_FLAG24 inconsistent: ${((RT_RULE_FLAG24.toFloat/total)*100).toInt}% \n")

      outputStream.writeChars(s"NRT_RULE_FLAG1 inconsistent: ${((NRT_RULE_FLAG1.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG2 inconsistent: ${((NRT_RULE_FLAG2.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG3 inconsistent: ${((NRT_RULE_FLAG3.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG4 inconsistent: ${((NRT_RULE_FLAG4.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG5 inconsistent: ${((NRT_RULE_FLAG5.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG6 inconsistent: ${((NRT_RULE_FLAG6.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG7 inconsistent: ${((NRT_RULE_FLAG7.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG8 inconsistent: ${((NRT_RULE_FLAG8.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG9 inconsistent: ${((NRT_RULE_FLAG9.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG10 inconsistent: ${((NRT_RULE_FLAG10.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG11 inconsistent: ${((NRT_RULE_FLAG11.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG12 inconsistent: ${((NRT_RULE_FLAG12.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG13 inconsistent: ${((NRT_RULE_FLAG13.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG14 inconsistent: ${((NRT_RULE_FLAG14.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG15 inconsistent: ${((NRT_RULE_FLAG15.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG16 inconsistent: ${((NRT_RULE_FLAG16.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG17 inconsistent: ${((NRT_RULE_FLAG17.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG18 inconsistent: ${((NRT_RULE_FLAG18.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG19 inconsistent: ${((NRT_RULE_FLAG19.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG20 inconsistent: ${((NRT_RULE_FLAG20.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG21 inconsistent: ${((NRT_RULE_FLAG21.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG22 inconsistent: ${((NRT_RULE_FLAG22.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG23 inconsistent: ${((NRT_RULE_FLAG23.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG24 inconsistent: ${((NRT_RULE_FLAG24.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG25 inconsistent: ${((NRT_RULE_FLAG25.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG26 inconsistent: ${((NRT_RULE_FLAG26.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG27 inconsistent: ${((NRT_RULE_FLAG27.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG28 inconsistent: ${((NRT_RULE_FLAG28.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG29 inconsistent: ${((NRT_RULE_FLAG29.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG30 inconsistent: ${((NRT_RULE_FLAG30.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG31 inconsistent: ${((NRT_RULE_FLAG31.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG32 inconsistent: ${((NRT_RULE_FLAG32.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG33 inconsistent: ${((NRT_RULE_FLAG33.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG34 inconsistent: ${((NRT_RULE_FLAG34.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG35 inconsistent: ${((NRT_RULE_FLAG35.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG36 inconsistent: ${((NRT_RULE_FLAG36.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG37 inconsistent: ${((NRT_RULE_FLAG37.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG38 inconsistent: ${((NRT_RULE_FLAG38.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG39 inconsistent: ${((NRT_RULE_FLAG39.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG40 inconsistent: ${((NRT_RULE_FLAG40.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG41 inconsistent: ${((NRT_RULE_FLAG41.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG42 inconsistent: ${((NRT_RULE_FLAG42.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG43 inconsistent: ${((NRT_RULE_FLAG43.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG44 inconsistent: ${((NRT_RULE_FLAG44.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG45 inconsistent: ${((NRT_RULE_FLAG45.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG46 inconsistent: ${((NRT_RULE_FLAG46.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG47 inconsistent: ${((NRT_RULE_FLAG47.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG48 inconsistent: ${((NRT_RULE_FLAG48.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG49 inconsistent: ${((NRT_RULE_FLAG49.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG50 inconsistent: ${((NRT_RULE_FLAG50.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG51 inconsistent: ${((NRT_RULE_FLAG51.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG52 inconsistent: ${((NRT_RULE_FLAG52.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG53 inconsistent: ${((NRT_RULE_FLAG53.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG54 inconsistent: ${((NRT_RULE_FLAG54.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG55 inconsistent: ${((NRT_RULE_FLAG55.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG56 inconsistent: ${((NRT_RULE_FLAG56.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG57 inconsistent: ${((NRT_RULE_FLAG57.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG58 inconsistent: ${((NRT_RULE_FLAG58.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG59 inconsistent: ${((NRT_RULE_FLAG59.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG60 inconsistent: ${((NRT_RULE_FLAG60.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG61 inconsistent: ${((NRT_RULE_FLAG61.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG62 inconsistent: ${((NRT_RULE_FLAG62.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG63 inconsistent: ${((NRT_RULE_FLAG63.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG64 inconsistent: ${((NRT_RULE_FLAG64.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG65 inconsistent: ${((NRT_RULE_FLAG65.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG66 inconsistent: ${((NRT_RULE_FLAG66.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG67 inconsistent: ${((NRT_RULE_FLAG67.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG68 inconsistent: ${((NRT_RULE_FLAG68.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG69 inconsistent: ${((NRT_RULE_FLAG69.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG70 inconsistent: ${((NRT_RULE_FLAG70.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG71 inconsistent: ${((NRT_RULE_FLAG71.toFloat/total)*100).toInt}% \n")
      outputStream.writeChars(s"NRT_RULE_FLAG72 inconsistent: ${((NRT_RULE_FLAG72.toFloat/total)*100).toInt}% \n")

      outputStream.flush()

    } finally {
      if (outputStream != null) {
        outputStream.close()
      }
    }
  }

  def removeParams(url: String): String = {
    if (url == null)
      return ""
    val splitter = url.split("&").filter(item => !item.startsWith("dashenId") && !item.startsWith("dashenCnt"))
    var res = splitter.mkString("&")

    if (res.startsWith("http://")) {
      res = res.substring(7)
    }else if (res.startsWith("https://")) {
      res = res.substring(8)
    }
    res
  }

  // should remove raptor=1 from rover URL
  def normalizeUrl(url: String): String = {
    if (url == null)
      return ""
    var result = url.replace("raptor=1", "")
    val lastChar = result.charAt(result.length - 1)
    if (lastChar == '&' || lastChar == '?') {
      result = result.substring(0, result.length - 1)
    }
    if (result.startsWith("http://")) {
      result = result.substring(7)
    }else if (result.startsWith("https://")) {
      result = result.substring(8)
    }
    result
  }


  def verifyResult(my: String, your: String): Boolean = {
    if (my == null && your == null)
      return true
    if (my != null && your != null)
      return my.equalsIgnoreCase(your)
    false
  }

  def verifyClick_TSResult(my: String, your: String): Boolean = {
    if (my == null && your == null)
      return true
    if (my != null && your != null) {
      val my_ts = my.split(" ")
      val your_ts = my.split(" ")
      if (my_ts(0).equalsIgnoreCase(your_ts(0)))
        return true
    }
    false
  }
}
