/*
 * mtid
 * Marketing id link system
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ebay.traffic.chocolate.flink.nrt.provider.mtid;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Idlink
 */
@javax.annotation.Generated(value = "com.ebay.swagger.templates.codegen.JavaEtsGenerator", date = "2020-07-01T13:18:40.427+08:00[Asia/Shanghai]")
@JsonPropertyOrder({ "account","guid","gadid","idfa","mgid","tpids" })
@JsonIgnoreProperties(ignoreUnknown = true)



public class Idlink implements Serializable {

  private static final long serialVersionUID = 1L;



  @JsonProperty("account")
  private List<String> account = new ArrayList<String>();

  @JsonProperty("guid")
  private List<String> guid = new ArrayList<String>();

  @JsonProperty("gadid")
  private List<String> gadid = new ArrayList<String>();

  @JsonProperty("idfa")
  private List<String> idfa = new ArrayList<String>();

  @JsonProperty("mgid")
  @JsonInclude(JsonInclude.Include.NON_NULL)
  private List<String> mgid = null;

  @JsonProperty("tpids")
  @JsonInclude(JsonInclude.Include.NON_NULL)
  private List<IdlinkTpids> tpids = null;


  /**
   * The user ID.
   * @return account
   */
  @JsonProperty("account")
  public List<String> getAccount() {
    return account;
  }


  @JsonProperty("account")
  public void setAccount(List<String> account) {
    this.account = account;
  }

  /**
   * The PGUID.
   * @return guid
   */
  @JsonProperty("guid")
  public List<String> getGuid() {
    return guid;
  }


  @JsonProperty("guid")
  public void setGuid(List<String> guid) {
    this.guid = guid;
  }

  /**
   * The google ad id.
   * @return gadid
   */
  @JsonProperty("gadid")
  public List<String> getGadid() {
    return gadid;
  }


  @JsonProperty("gadid")
  public void setGadid(List<String> gadid) {
    this.gadid = gadid;
  }

  /**
   * The ios identifier.
   * @return idfa
   */
  @JsonProperty("idfa")
  public List<String> getIdfa() {
    return idfa;
  }


  @JsonProperty("idfa")
  public void setIdfa(List<String> idfa) {
    this.idfa = idfa;
  }

  /**
   * The MGID of the device.
   * @return mgid
   */
  @JsonProperty("mgid")
  public List<String> getMgid() {
    return mgid;
  }


  @JsonProperty("mgid")
  public void setMgid(List<String> mgid) {
    this.mgid = mgid;
  }

  /**
   * Third party ids.
   * @return tpids
   */
  @JsonProperty("tpids")
  public List<IdlinkTpids> getTpids() {
    return tpids;
  }


  @JsonProperty("tpids")
  public void setTpids(List<IdlinkTpids> tpids) {
    this.tpids = tpids;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Idlink {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    gadid: ").append(toIndentedString(gadid)).append("\n");
    sb.append("    idfa: ").append(toIndentedString(idfa)).append("\n");
    sb.append("    mgid: ").append(toIndentedString(mgid)).append("\n");
    sb.append("    tpids: ").append(toIndentedString(tpids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
