insert into table choco_data.IMK_RVR_TRCKNG_EVENT_DIFF_TMP
select '#{dt}','imk',count(*) FROM (select * from choco_data.imk_rvr_trckng_event_v2 where dt='#{dt}') new
FULL outer join (select * from choco_data.imk_rvr_trckng_event where dt='#{dt}') imk
on new.batch_id <=> imk.batch_id and
new.file_id <=> imk.file_id and
new.file_schm_vrsn <=> imk.file_schm_vrsn and
new.rvr_id <=> imk.rvr_id and
new.srvd_pstn <=> imk.srvd_pstn and
new.rvr_cmnd_type_cd <=> imk.rvr_cmnd_type_cd and
new.rvr_chnl_type_cd <=> imk.rvr_chnl_type_cd and
new.cntry_cd <=> imk.cntry_cd and
new.lang_cd <=> imk.lang_cd and
new.trckng_prtnr_id <=> imk.trckng_prtnr_id and
new.cguid <=> imk.cguid and
new.guid <=> imk.guid and
new.user_id <=> imk.user_id and
new.clnt_remote_ip <=> imk.clnt_remote_ip and
new.brwsr_type_id <=> imk.brwsr_type_id and
new.brwsr_name <=> imk.brwsr_name and
new.rfrr_dmn_name <=> imk.rfrr_dmn_name and
new.rfrr_url <=> imk.rfrr_url and
new.url_encrptd_yn_ind <=> imk.url_encrptd_yn_ind and
new.pblshr_id <=> imk.pblshr_id and
new.lndng_page_dmn_name <=> imk.lndng_page_dmn_name and
new.lndng_page_url <=> imk.lndng_page_url and
new.user_query <=> imk.user_query and
new.rule_bit_flag_strng <=> imk.rule_bit_flag_strng and
new.event_ts <=> imk.event_ts and
new.dflt_bhrv_id <=> imk.dflt_bhrv_id and
new.src_rotation_id <=> imk.src_rotation_id and
new.dst_rotation_id <=> imk.dst_rotation_id and
new.user_map_ind <=> imk.user_map_ind and
new.dst_client_id <=> imk.dst_client_id and
new.creative_id <=> imk.creative_id and
new.test_ctrl_flag <=> imk.test_ctrl_flag and
new.mfe_id <=> imk.mfe_id and
new.kw_id <=> imk.kw_id and
new.keyword <=> imk.keyword and
new.mt_id <=> imk.mt_id and
new.crlp <=> imk.crlp and
new.geo_id <=> imk.geo_id and
new.item_id <=> imk.item_id and
new.transaction_type <=> imk.transaction_type and
new.transaction_id <=> imk.transaction_id and
new.cart_id <=> imk.cart_id and
new.extrnl_cookie <=> imk.extrnl_cookie and
new.ebay_site_id <=> imk.ebay_site_id and
new.rvr_url <=> imk.rvr_url and
new.cre_date <=> imk.cre_date and
new.cre_user <=> imk.cre_user and
new.upd_date <=> imk.upd_date and
new.upd_user <=> imk.upd_user and
new.dt<=>imk.dt
WHERE new.rvr_id is null or imk.rvr_id is null