CREATE EXTERNAL TABLE `choco_data.IMK_RVR_TRCKNG_EVENT_TMP`(
  `batch_id` string,
  `file_id` int,
  `file_schm_vrsn` int,
  `rvr_id` bigint,
  `srvd_pstn` tinyint,
  `rvr_cmnd_type_cd` string,
  `rvr_chnl_type_cd` string,
  `cntry_cd` string,
  `lang_cd` string,
  `trckng_prtnr_id` tinyint,
  `cguid` string,
  `guid` string,
  `user_id` bigint,
  `clnt_remote_ip` string,
  `brwsr_type_id` tinyint,
  `brwsr_name` string,
  `rfrr_dmn_name` string,
  `rfrr_url` string,
  `url_encrptd_yn_ind` tinyint,
  `pblshr_id` string,
  `lndng_page_dmn_name` string,
  `lndng_page_url` string,
  `user_query` string,
  `rule_bit_flag_strng` string,
  `event_ts` string,
  `dflt_bhrv_id` tinyint,
  `src_rotation_id` bigint,
  `dst_rotation_id` bigint,
  `user_map_ind` string,
  `dst_client_id` int,
  `creative_id` bigint,
  `test_ctrl_flag` tinyint,
  `mfe_id` int,
  `kw_id` bigint,
  `keyword` string,
  `mt_id` string,
  `crlp` string,
  `geo_id` string,
  `item_id` string,
  `transaction_type` string,
  `transaction_id` string,
  `cart_id` string,
  `extrnl_cookie` string,
  `ebay_site_id` string,
  `rvr_url` string,
  `flex_field_vrsn_num` smallint,
  `flex_field_1` string,
  `flex_field_2` string,
  `flex_field_3` string,
  `flex_field_4` string,
  `flex_field_5` string,
  `flex_field_6` string,
  `flex_field_7` string,
  `flex_field_8` string,
  `flex_field_9` string,
  `flex_field_10` string,
  `flex_field_11` string,
  `flex_field_12` string,
  `flex_field_13` string,
  `flex_field_14` string,
  `flex_field_15` string,
  `flex_field_16` string,
  `flex_field_17` string,
  `flex_field_18` string,
  `flex_field_19` string,
  `flex_field_20` string,
  `perf_track_name_value` string,
  `cre_date` string,
  `cre_user` string,
  `upd_date` string,
  `upd_user` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'viewfs://apollo-rno/apps/b_marketing_tracking/delta_test/imk_tmp'
TBLPROPERTIES (
  'transient_lastDdlTime'='1601444855')