type=command
dependencies=distcpImkToRenoAndHercules
command=bash SubmitJob.sh "SLC" "/datashare/mkttracking/jobs/chocolate-sparknrt/bin/prod" "./touchImkHourlyDone.sh hdfs://slickha/apps/tracking-events-workdir hdfs://slickha/apps/tracking-events-workdir/calCrabTransformWatermark hdfs://slickha/apps/tracking-events/watch"
failure.emails=jialili1@ebay.com, fechen@ebay.com, xiangli4@ebay.com, yliu29@ebay.com, huiclu@ebay.com, shuangxu@ebay.com, lxiong1@ebay.com, zhofan@ebay.com, zjian@ebay.com, zhiyuawang@ebay.com