type=command
dependencies=distcpImkToRenoAndHercules_v2
command=bash SubmitJob.sh "SLC" "/datashare/mkttracking/jobs/chocolate-sparknrt/bin/prod" "./touchImkHourlyDone.sh hdfs://slickha/apps/tracking-events-workdir hdfs://slickha/apps/tracking-events-workdir-imk/calCrabTransformWatermark hdfs://slickha/apps/tracking-events-imk/watch"
failure.emails=jialili1@ebay.com, fechen@ebay.com, xiangli4@ebay.com, yliu29@ebay.com, huiclu@ebay.com, shuangxu@ebay.com, zhofan@ebay.com, zhiyuawang@ebay.com, zjian@ebay.com, yli19@ebay.com, yyang28@ebay.com