/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.app.raptor.chocolate.avro.versions;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FilterMessageV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5416398920540482642L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FilterMessageV2\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro.versions\",\"fields\":[{\"name\":\"snapshot_id\",\"type\":\"long\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"publisher_id\",\"type\":\"long\"},{\"name\":\"campaign_id\",\"type\":\"long\"},{\"name\":\"request_headers\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"uri\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"response_headers\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rt_rule_flags\",\"type\":\"long\"},{\"name\":\"nrt_rule_flags\",\"type\":\"long\"},{\"name\":\"channel_action\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelAction\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"symbols\":[\"CLICK\",\"IMPRESSION\",\"VIEWABLE\",\"SERVE\",\"PAGE_IMP\",\"VIEW_ITEM\",\"VIEW_TIME\",\"APP_FIRST_START\"]}},{\"name\":\"channel_type\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelType\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"symbols\":[\"DEFAULT\",\"EPN\",\"DISPLAY\",\"PAID_SEARCH\",\"SOCIAL_MEDIA\",\"PAID_SOCIAL\"]}},{\"name\":\"http_method\",\"type\":{\"type\":\"enum\",\"name\":\"HttpMethod\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"symbols\":[\"CONNECT\",\"DELETE\",\"GET\",\"HEAD\",\"OPTIONS\",\"PATCH\",\"POST\",\"PUT\",\"TRACE\"]}},{\"name\":\"snid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"is_tracked\",\"type\":\"boolean\",\"default\":false}],\"pk\":[\"snapshot_id\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FilterMessageV2> ENCODER =
      new BinaryMessageEncoder<FilterMessageV2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FilterMessageV2> DECODER =
      new BinaryMessageDecoder<FilterMessageV2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FilterMessageV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FilterMessageV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FilterMessageV2>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FilterMessageV2 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FilterMessageV2 from a ByteBuffer. */
  public static FilterMessageV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long snapshot_id;
  @Deprecated public long timestamp;
  @Deprecated public long publisher_id;
  @Deprecated public long campaign_id;
  @Deprecated public java.lang.String request_headers;
  @Deprecated public java.lang.String uri;
  @Deprecated public java.lang.String response_headers;
  @Deprecated public long rt_rule_flags;
  @Deprecated public long nrt_rule_flags;
  @Deprecated public com.ebay.app.raptor.chocolate.avro.ChannelAction channel_action;
  @Deprecated public com.ebay.app.raptor.chocolate.avro.ChannelType channel_type;
  @Deprecated public com.ebay.app.raptor.chocolate.avro.HttpMethod http_method;
  @Deprecated public java.lang.String snid;
  @Deprecated public boolean is_tracked;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FilterMessageV2() {}

  /**
   * All-args constructor.
   * @param snapshot_id The new value for snapshot_id
   * @param timestamp The new value for timestamp
   * @param publisher_id The new value for publisher_id
   * @param campaign_id The new value for campaign_id
   * @param request_headers The new value for request_headers
   * @param uri The new value for uri
   * @param response_headers The new value for response_headers
   * @param rt_rule_flags The new value for rt_rule_flags
   * @param nrt_rule_flags The new value for nrt_rule_flags
   * @param channel_action The new value for channel_action
   * @param channel_type The new value for channel_type
   * @param http_method The new value for http_method
   * @param snid The new value for snid
   * @param is_tracked The new value for is_tracked
   */
  public FilterMessageV2(java.lang.Long snapshot_id, java.lang.Long timestamp, java.lang.Long publisher_id, java.lang.Long campaign_id, java.lang.String request_headers, java.lang.String uri, java.lang.String response_headers, java.lang.Long rt_rule_flags, java.lang.Long nrt_rule_flags, com.ebay.app.raptor.chocolate.avro.ChannelAction channel_action, com.ebay.app.raptor.chocolate.avro.ChannelType channel_type, com.ebay.app.raptor.chocolate.avro.HttpMethod http_method, java.lang.String snid, java.lang.Boolean is_tracked) {
    this.snapshot_id = snapshot_id;
    this.timestamp = timestamp;
    this.publisher_id = publisher_id;
    this.campaign_id = campaign_id;
    this.request_headers = request_headers;
    this.uri = uri;
    this.response_headers = response_headers;
    this.rt_rule_flags = rt_rule_flags;
    this.nrt_rule_flags = nrt_rule_flags;
    this.channel_action = channel_action;
    this.channel_type = channel_type;
    this.http_method = http_method;
    this.snid = snid;
    this.is_tracked = is_tracked;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return snapshot_id;
    case 1: return timestamp;
    case 2: return publisher_id;
    case 3: return campaign_id;
    case 4: return request_headers;
    case 5: return uri;
    case 6: return response_headers;
    case 7: return rt_rule_flags;
    case 8: return nrt_rule_flags;
    case 9: return channel_action;
    case 10: return channel_type;
    case 11: return http_method;
    case 12: return snid;
    case 13: return is_tracked;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: snapshot_id = (java.lang.Long)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: publisher_id = (java.lang.Long)value$; break;
    case 3: campaign_id = (java.lang.Long)value$; break;
    case 4: request_headers = (java.lang.String)value$; break;
    case 5: uri = (java.lang.String)value$; break;
    case 6: response_headers = (java.lang.String)value$; break;
    case 7: rt_rule_flags = (java.lang.Long)value$; break;
    case 8: nrt_rule_flags = (java.lang.Long)value$; break;
    case 9: channel_action = (com.ebay.app.raptor.chocolate.avro.ChannelAction)value$; break;
    case 10: channel_type = (com.ebay.app.raptor.chocolate.avro.ChannelType)value$; break;
    case 11: http_method = (com.ebay.app.raptor.chocolate.avro.HttpMethod)value$; break;
    case 12: snid = (java.lang.String)value$; break;
    case 13: is_tracked = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'snapshot_id' field.
   * @return The value of the 'snapshot_id' field.
   */
  public java.lang.Long getSnapshotId() {
    return snapshot_id;
  }

  /**
   * Sets the value of the 'snapshot_id' field.
   * @param value the value to set.
   */
  public void setSnapshotId(java.lang.Long value) {
    this.snapshot_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'publisher_id' field.
   * @return The value of the 'publisher_id' field.
   */
  public java.lang.Long getPublisherId() {
    return publisher_id;
  }

  /**
   * Sets the value of the 'publisher_id' field.
   * @param value the value to set.
   */
  public void setPublisherId(java.lang.Long value) {
    this.publisher_id = value;
  }

  /**
   * Gets the value of the 'campaign_id' field.
   * @return The value of the 'campaign_id' field.
   */
  public java.lang.Long getCampaignId() {
    return campaign_id;
  }

  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(java.lang.Long value) {
    this.campaign_id = value;
  }

  /**
   * Gets the value of the 'request_headers' field.
   * @return The value of the 'request_headers' field.
   */
  public java.lang.String getRequestHeaders() {
    return request_headers;
  }

  /**
   * Sets the value of the 'request_headers' field.
   * @param value the value to set.
   */
  public void setRequestHeaders(java.lang.String value) {
    this.request_headers = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return The value of the 'uri' field.
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.String value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'response_headers' field.
   * @return The value of the 'response_headers' field.
   */
  public java.lang.String getResponseHeaders() {
    return response_headers;
  }

  /**
   * Sets the value of the 'response_headers' field.
   * @param value the value to set.
   */
  public void setResponseHeaders(java.lang.String value) {
    this.response_headers = value;
  }

  /**
   * Gets the value of the 'rt_rule_flags' field.
   * @return The value of the 'rt_rule_flags' field.
   */
  public java.lang.Long getRtRuleFlags() {
    return rt_rule_flags;
  }

  /**
   * Sets the value of the 'rt_rule_flags' field.
   * @param value the value to set.
   */
  public void setRtRuleFlags(java.lang.Long value) {
    this.rt_rule_flags = value;
  }

  /**
   * Gets the value of the 'nrt_rule_flags' field.
   * @return The value of the 'nrt_rule_flags' field.
   */
  public java.lang.Long getNrtRuleFlags() {
    return nrt_rule_flags;
  }

  /**
   * Sets the value of the 'nrt_rule_flags' field.
   * @param value the value to set.
   */
  public void setNrtRuleFlags(java.lang.Long value) {
    this.nrt_rule_flags = value;
  }

  /**
   * Gets the value of the 'channel_action' field.
   * @return The value of the 'channel_action' field.
   */
  public com.ebay.app.raptor.chocolate.avro.ChannelAction getChannelAction() {
    return channel_action;
  }

  /**
   * Sets the value of the 'channel_action' field.
   * @param value the value to set.
   */
  public void setChannelAction(com.ebay.app.raptor.chocolate.avro.ChannelAction value) {
    this.channel_action = value;
  }

  /**
   * Gets the value of the 'channel_type' field.
   * @return The value of the 'channel_type' field.
   */
  public com.ebay.app.raptor.chocolate.avro.ChannelType getChannelType() {
    return channel_type;
  }

  /**
   * Sets the value of the 'channel_type' field.
   * @param value the value to set.
   */
  public void setChannelType(com.ebay.app.raptor.chocolate.avro.ChannelType value) {
    this.channel_type = value;
  }

  /**
   * Gets the value of the 'http_method' field.
   * @return The value of the 'http_method' field.
   */
  public com.ebay.app.raptor.chocolate.avro.HttpMethod getHttpMethod() {
    return http_method;
  }

  /**
   * Sets the value of the 'http_method' field.
   * @param value the value to set.
   */
  public void setHttpMethod(com.ebay.app.raptor.chocolate.avro.HttpMethod value) {
    this.http_method = value;
  }

  /**
   * Gets the value of the 'snid' field.
   * @return The value of the 'snid' field.
   */
  public java.lang.String getSnid() {
    return snid;
  }

  /**
   * Sets the value of the 'snid' field.
   * @param value the value to set.
   */
  public void setSnid(java.lang.String value) {
    this.snid = value;
  }

  /**
   * Gets the value of the 'is_tracked' field.
   * @return The value of the 'is_tracked' field.
   */
  public java.lang.Boolean getIsTracked() {
    return is_tracked;
  }

  /**
   * Sets the value of the 'is_tracked' field.
   * @param value the value to set.
   */
  public void setIsTracked(java.lang.Boolean value) {
    this.is_tracked = value;
  }

  /**
   * Creates a new FilterMessageV2 RecordBuilder.
   * @return A new FilterMessageV2 RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder newBuilder() {
    return new com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder();
  }

  /**
   * Creates a new FilterMessageV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FilterMessageV2 RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder other) {
    return new com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder(other);
  }

  /**
   * Creates a new FilterMessageV2 RecordBuilder by copying an existing FilterMessageV2 instance.
   * @param other The existing instance to copy.
   * @return A new FilterMessageV2 RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2 other) {
    return new com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder(other);
  }

  /**
   * RecordBuilder for FilterMessageV2 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FilterMessageV2>
    implements org.apache.avro.data.RecordBuilder<FilterMessageV2> {

    private long snapshot_id;
    private long timestamp;
    private long publisher_id;
    private long campaign_id;
    private java.lang.String request_headers;
    private java.lang.String uri;
    private java.lang.String response_headers;
    private long rt_rule_flags;
    private long nrt_rule_flags;
    private com.ebay.app.raptor.chocolate.avro.ChannelAction channel_action;
    private com.ebay.app.raptor.chocolate.avro.ChannelType channel_type;
    private com.ebay.app.raptor.chocolate.avro.HttpMethod http_method;
    private java.lang.String snid;
    private boolean is_tracked;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.snapshot_id)) {
        this.snapshot_id = data().deepCopy(fields()[0].schema(), other.snapshot_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publisher_id)) {
        this.publisher_id = data().deepCopy(fields()[2].schema(), other.publisher_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[3].schema(), other.campaign_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.request_headers)) {
        this.request_headers = data().deepCopy(fields()[4].schema(), other.request_headers);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.uri)) {
        this.uri = data().deepCopy(fields()[5].schema(), other.uri);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.response_headers)) {
        this.response_headers = data().deepCopy(fields()[6].schema(), other.response_headers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rt_rule_flags)) {
        this.rt_rule_flags = data().deepCopy(fields()[7].schema(), other.rt_rule_flags);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.nrt_rule_flags)) {
        this.nrt_rule_flags = data().deepCopy(fields()[8].schema(), other.nrt_rule_flags);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.channel_action)) {
        this.channel_action = data().deepCopy(fields()[9].schema(), other.channel_action);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.channel_type)) {
        this.channel_type = data().deepCopy(fields()[10].schema(), other.channel_type);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.http_method)) {
        this.http_method = data().deepCopy(fields()[11].schema(), other.http_method);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.snid)) {
        this.snid = data().deepCopy(fields()[12].schema(), other.snid);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.is_tracked)) {
        this.is_tracked = data().deepCopy(fields()[13].schema(), other.is_tracked);
        fieldSetFlags()[13] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FilterMessageV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.snapshot_id)) {
        this.snapshot_id = data().deepCopy(fields()[0].schema(), other.snapshot_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publisher_id)) {
        this.publisher_id = data().deepCopy(fields()[2].schema(), other.publisher_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[3].schema(), other.campaign_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.request_headers)) {
        this.request_headers = data().deepCopy(fields()[4].schema(), other.request_headers);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.uri)) {
        this.uri = data().deepCopy(fields()[5].schema(), other.uri);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.response_headers)) {
        this.response_headers = data().deepCopy(fields()[6].schema(), other.response_headers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rt_rule_flags)) {
        this.rt_rule_flags = data().deepCopy(fields()[7].schema(), other.rt_rule_flags);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.nrt_rule_flags)) {
        this.nrt_rule_flags = data().deepCopy(fields()[8].schema(), other.nrt_rule_flags);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.channel_action)) {
        this.channel_action = data().deepCopy(fields()[9].schema(), other.channel_action);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.channel_type)) {
        this.channel_type = data().deepCopy(fields()[10].schema(), other.channel_type);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.http_method)) {
        this.http_method = data().deepCopy(fields()[11].schema(), other.http_method);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.snid)) {
        this.snid = data().deepCopy(fields()[12].schema(), other.snid);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.is_tracked)) {
        this.is_tracked = data().deepCopy(fields()[13].schema(), other.is_tracked);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'snapshot_id' field.
      * @return The value.
      */
    public java.lang.Long getSnapshotId() {
      return snapshot_id;
    }

    /**
      * Sets the value of the 'snapshot_id' field.
      * @param value The value of 'snapshot_id'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setSnapshotId(long value) {
      validate(fields()[0], value);
      this.snapshot_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'snapshot_id' field has been set.
      * @return True if the 'snapshot_id' field has been set, false otherwise.
      */
    public boolean hasSnapshotId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'snapshot_id' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearSnapshotId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisher_id' field.
      * @return The value.
      */
    public java.lang.Long getPublisherId() {
      return publisher_id;
    }

    /**
      * Sets the value of the 'publisher_id' field.
      * @param value The value of 'publisher_id'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setPublisherId(long value) {
      validate(fields()[2], value);
      this.publisher_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publisher_id' field has been set.
      * @return True if the 'publisher_id' field has been set, false otherwise.
      */
    public boolean hasPublisherId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'publisher_id' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearPublisherId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaign_id' field.
      * @return The value.
      */
    public java.lang.Long getCampaignId() {
      return campaign_id;
    }

    /**
      * Sets the value of the 'campaign_id' field.
      * @param value The value of 'campaign_id'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setCampaignId(long value) {
      validate(fields()[3], value);
      this.campaign_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_id' field has been set.
      * @return True if the 'campaign_id' field has been set, false otherwise.
      */
    public boolean hasCampaignId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'campaign_id' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearCampaignId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'request_headers' field.
      * @return The value.
      */
    public java.lang.String getRequestHeaders() {
      return request_headers;
    }

    /**
      * Sets the value of the 'request_headers' field.
      * @param value The value of 'request_headers'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setRequestHeaders(java.lang.String value) {
      validate(fields()[4], value);
      this.request_headers = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'request_headers' field has been set.
      * @return True if the 'request_headers' field has been set, false otherwise.
      */
    public boolean hasRequestHeaders() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'request_headers' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearRequestHeaders() {
      request_headers = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * @return The value.
      */
    public java.lang.String getUri() {
      return uri;
    }

    /**
      * Sets the value of the 'uri' field.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setUri(java.lang.String value) {
      validate(fields()[5], value);
      this.uri = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'uri' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearUri() {
      uri = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'response_headers' field.
      * @return The value.
      */
    public java.lang.String getResponseHeaders() {
      return response_headers;
    }

    /**
      * Sets the value of the 'response_headers' field.
      * @param value The value of 'response_headers'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setResponseHeaders(java.lang.String value) {
      validate(fields()[6], value);
      this.response_headers = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'response_headers' field has been set.
      * @return True if the 'response_headers' field has been set, false otherwise.
      */
    public boolean hasResponseHeaders() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'response_headers' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearResponseHeaders() {
      response_headers = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'rt_rule_flags' field.
      * @return The value.
      */
    public java.lang.Long getRtRuleFlags() {
      return rt_rule_flags;
    }

    /**
      * Sets the value of the 'rt_rule_flags' field.
      * @param value The value of 'rt_rule_flags'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setRtRuleFlags(long value) {
      validate(fields()[7], value);
      this.rt_rule_flags = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'rt_rule_flags' field has been set.
      * @return True if the 'rt_rule_flags' field has been set, false otherwise.
      */
    public boolean hasRtRuleFlags() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'rt_rule_flags' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearRtRuleFlags() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'nrt_rule_flags' field.
      * @return The value.
      */
    public java.lang.Long getNrtRuleFlags() {
      return nrt_rule_flags;
    }

    /**
      * Sets the value of the 'nrt_rule_flags' field.
      * @param value The value of 'nrt_rule_flags'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setNrtRuleFlags(long value) {
      validate(fields()[8], value);
      this.nrt_rule_flags = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'nrt_rule_flags' field has been set.
      * @return True if the 'nrt_rule_flags' field has been set, false otherwise.
      */
    public boolean hasNrtRuleFlags() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'nrt_rule_flags' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearNrtRuleFlags() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel_action' field.
      * @return The value.
      */
    public com.ebay.app.raptor.chocolate.avro.ChannelAction getChannelAction() {
      return channel_action;
    }

    /**
      * Sets the value of the 'channel_action' field.
      * @param value The value of 'channel_action'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setChannelAction(com.ebay.app.raptor.chocolate.avro.ChannelAction value) {
      validate(fields()[9], value);
      this.channel_action = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'channel_action' field has been set.
      * @return True if the 'channel_action' field has been set, false otherwise.
      */
    public boolean hasChannelAction() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'channel_action' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearChannelAction() {
      channel_action = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel_type' field.
      * @return The value.
      */
    public com.ebay.app.raptor.chocolate.avro.ChannelType getChannelType() {
      return channel_type;
    }

    /**
      * Sets the value of the 'channel_type' field.
      * @param value The value of 'channel_type'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setChannelType(com.ebay.app.raptor.chocolate.avro.ChannelType value) {
      validate(fields()[10], value);
      this.channel_type = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'channel_type' field has been set.
      * @return True if the 'channel_type' field has been set, false otherwise.
      */
    public boolean hasChannelType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'channel_type' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearChannelType() {
      channel_type = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'http_method' field.
      * @return The value.
      */
    public com.ebay.app.raptor.chocolate.avro.HttpMethod getHttpMethod() {
      return http_method;
    }

    /**
      * Sets the value of the 'http_method' field.
      * @param value The value of 'http_method'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setHttpMethod(com.ebay.app.raptor.chocolate.avro.HttpMethod value) {
      validate(fields()[11], value);
      this.http_method = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'http_method' field has been set.
      * @return True if the 'http_method' field has been set, false otherwise.
      */
    public boolean hasHttpMethod() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'http_method' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearHttpMethod() {
      http_method = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'snid' field.
      * @return The value.
      */
    public java.lang.String getSnid() {
      return snid;
    }

    /**
      * Sets the value of the 'snid' field.
      * @param value The value of 'snid'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setSnid(java.lang.String value) {
      validate(fields()[12], value);
      this.snid = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'snid' field has been set.
      * @return True if the 'snid' field has been set, false otherwise.
      */
    public boolean hasSnid() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'snid' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearSnid() {
      snid = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_tracked' field.
      * @return The value.
      */
    public java.lang.Boolean getIsTracked() {
      return is_tracked;
    }

    /**
      * Sets the value of the 'is_tracked' field.
      * @param value The value of 'is_tracked'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder setIsTracked(boolean value) {
      validate(fields()[13], value);
      this.is_tracked = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'is_tracked' field has been set.
      * @return True if the 'is_tracked' field has been set, false otherwise.
      */
    public boolean hasIsTracked() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'is_tracked' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.versions.FilterMessageV2.Builder clearIsTracked() {
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FilterMessageV2 build() {
      try {
        FilterMessageV2 record = new FilterMessageV2();
        record.snapshot_id = fieldSetFlags()[0] ? this.snapshot_id : (java.lang.Long) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.publisher_id = fieldSetFlags()[2] ? this.publisher_id : (java.lang.Long) defaultValue(fields()[2]);
        record.campaign_id = fieldSetFlags()[3] ? this.campaign_id : (java.lang.Long) defaultValue(fields()[3]);
        record.request_headers = fieldSetFlags()[4] ? this.request_headers : (java.lang.String) defaultValue(fields()[4]);
        record.uri = fieldSetFlags()[5] ? this.uri : (java.lang.String) defaultValue(fields()[5]);
        record.response_headers = fieldSetFlags()[6] ? this.response_headers : (java.lang.String) defaultValue(fields()[6]);
        record.rt_rule_flags = fieldSetFlags()[7] ? this.rt_rule_flags : (java.lang.Long) defaultValue(fields()[7]);
        record.nrt_rule_flags = fieldSetFlags()[8] ? this.nrt_rule_flags : (java.lang.Long) defaultValue(fields()[8]);
        record.channel_action = fieldSetFlags()[9] ? this.channel_action : (com.ebay.app.raptor.chocolate.avro.ChannelAction) defaultValue(fields()[9]);
        record.channel_type = fieldSetFlags()[10] ? this.channel_type : (com.ebay.app.raptor.chocolate.avro.ChannelType) defaultValue(fields()[10]);
        record.http_method = fieldSetFlags()[11] ? this.http_method : (com.ebay.app.raptor.chocolate.avro.HttpMethod) defaultValue(fields()[11]);
        record.snid = fieldSetFlags()[12] ? this.snid : (java.lang.String) defaultValue(fields()[12]);
        record.is_tracked = fieldSetFlags()[13] ? this.is_tracked : (java.lang.Boolean) defaultValue(fields()[13]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FilterMessageV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<FilterMessageV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FilterMessageV2>
    READER$ = (org.apache.avro.io.DatumReader<FilterMessageV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
