---
openapi: 3.0.0
servers:
  - url: 'http://api.ebay.com/marketingtracking/v1'
    description: Marketing tracking collection services
info:
  description: >-
    marketing tracking compoent to receive marketing events
  version: 1.0.0
  title: service-tracking-events
paths:
  /track:
    post:
      summary: Send one marketing event to track
      description: Send one marketing event to track
      tags:
        - track
      operationId: track
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnifiedTrackingEvent'
  /roi:
    post:
      summary: Send roi event to marketing tracking
      description: Send roi event to marketing tracking
      tags:
        - roi
      operationId: roi
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ROIEvent'
  /events:
    post:
      summary: Send one click event to marketing tracking
      description: Send one event to marketing tracking
      tags:
        - events
      operationId: event
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
  /getVersion:
    get:
      summary: Get api version
      description: Get marketing tracking api version
      tags:
        - version
      operationId: version
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '200':
          description: version number
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
  /impression:
    post:
      summary: Send one impression event to marketing tracking
      description: Send one event to marketing tracking
      tags:
        - impression
      operationId: impression
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
  /sync:
    post:
      summary: Send sync event to mcs
      description: Send sync event to mcs
      tags:
        - sync
      operationId: sync
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
  /akamai:
    post:
      summary: Send akamai event to marketing tracking
      description: Send akamai event to marketing tracking
      tags:
        - akamai
      operationId: akamai
      security:
        - app_scope_auth:
            - 'https://api.ebay.com/oauth/scope/@public'
            - 'https://api.ebay.com/oauth/scope/base@public'
            - 'https://api.ebay.com/oauth/scope/experience@public'
      responses:
        '201':
          description: Created
        '400':
          description: Rejected due to message format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: The call was unsuccessful due to exceptions on the Server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AkamaiEvent'

components:
  securitySchemes:
    app_scope_auth:
      type: oauth2
      description: >-
        The security definitions for this API. Please check individual
        operations for applicable scopes.
      flows:
        clientCredentials:
          tokenUrl: 'https://api.ebay.com/identity/v1/oauth2/token'
          scopes:
            'https://api.ebay.com/oauth/scope/@public': This scope would allow public access.
            'https://api.ebay.com/oauth/scope/base@public': This scope would allow base public access.
            'https://api.ebay.com/oauth/scope/experience@public': This scope would allow experience public access.
  schemas:
    UnifiedTrackingEvent:
      type: object
      properties:
        producerEventId:
          type: string
          description: 'Event id at producer level'
          example: '18c244e5-0ee3-4b0e-b283-4efb379bee44'
        producerEventTs:
          type: integer
          format: int64
          description: 'Timestamp when the producer calls the tracking service'
          example: 1604463171000
        rlogId:
          type: string
          description: 'rlogId'
          example: 't6klaook%60b0%3D%3C%3Dpieojbnkmcc4%3B(5574425-1759175a140-0x1902'
        trackingId:
          type: string
          description: 'Id used to associate the marketing system behavior and the user behavior'
          example: '0AD3335D-36089192FCC-017529D1F00D-00000000027EEF2B'
        userId:
          type: integer
          format: int64
          description: 'Oracle id'
          example: '1626162'
        publicUserId:
          type: string
          description: 'Public user id'
          example: '1626162'
        encryptedUserId:
          type: integer
          format: int64
          description: 'Encrypted user id'
          example: '542525556'
        guid:
          type: string
          description: 'guid'
          example: '8b34ef1d1740a4d724970d78eec8ee4c'
        idfa:
          type: string
          description: 'ios identifier'
          example: '30255BCE-4CDA-4F62-91DC-4758FDFF8512'
        gadid:
          type: string
          description: 'android ad identifier'
          example: '035911ea-467d-4056-903b-65cf44f5633b'
        deviceId:
          type: string
          description: 'This is ebay mobile app generated unique id for each app installation. It is usually used in request header X-EBAY3PP-DEVICE-ID for each API call.'
          example: '035911ea-467d-4056-903b-65cf44f5633b'
        channelType:
          type: string
          description: 'Channel identifier'
          example: 'MRKT_EMAIL'
        actionType:
          type: string
          description: 'Action identifier'
          example: 'CLICK'
        partner:
          type: string
          description: 'For epn publisher id, for display partner id. For CM, we have adobe, SMTP, Send Grid...'
          example: '16352125'
        campaignId:
          type: string
          description: 'Campaign id'
          example: '2231121'
        siteId:
          type: integer
          description: 'eBay site id'
          example: 0
        url:
          type: string
          description: 'Tracking url'
          example: 'https://www.ebay.com/i/1312121?mkevt=1&mkcid=2'
        referer:
          type: string
          description: 'Referer of the tracking request'
          example: 'https://www.google.com/'
        userAgent:
          type: string
          description: 'Client full user agent name'
          example: 'Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36'
        appVersion:
          type: string
          description: 'eBay app version'
          example: '5.7.0'
        deviceType:
          type: string
          description: 'Operating system of the device'
          example: 'iOS'
        service:
          type: string
          description: 'Service name of the producer'
          example: 'Chocolate'
        server:
          type: string
          description: 'The server which is calling the tracking service'
          example: 'rnochocolis-123.stratus.ebay.com'
        remoteIp:
          type: string
          description: 'End user remote IP'
          example: '202.76.240.67'
        pageId:
          type: integer
          description: 'Corresponding page id in sojourner'
          example: 3084
        geoId:
          type: integer
          description: 'Geo id of the end user'
          example: 1
        payload:
          type: object
          description: Tracking event payload
          additionalProperties:
            type: string
    Event:
      type: object
      properties:
        targetUrl:
          type: string
          example: 'htttps://www.ebay.com/deals'
        referrer:
          type: string
          example: 'htttps://www.google.com'
        payload:
          type: object
          description: Tracking event payload
          properties:
            pageId:
              type: integer
              format: int64
              description: page id, mandotary for notification
              example: 2054081
            tags:
              type: object
              description: Map<String, String> for soj tags
              additionalProperties:
                type: string
            checkoutAPIClickTs:
              type: string
              description: checkoutAPIClickTs, mandotary for click from checkoutAPI
              example: "1576108800000"
            placeOfferAPIClickTs:
              type: string
              description: placeOfferAPIClickTs, mandotary for click from placeofferAPI
              example: "1576108800000"
    ROIEvent:
      type: object
      properties:
        transType:
          type: "string"
          example: "BO-MobileApp"
        uniqueTransactionId:
          type: "string"
          example: "1677235978009"
        itemId:
          type: "string"
          example: "192658398245"
        transactionTimestamp:
          type: "string"
          example: "1576108800000"
        payload:
          type: object
          example: '{"transactionTimestamp":"aaa","siteId":"bbbb"}'
          additionalProperties:
            type: string
    AkamaiEvent:
      type: object
      properties:
        version:
          type: string
        ewUsageInfo:
          type: string
        ewExecutionInfo:
          type: string
        country:
          type: string
        city:
          type: string
        state:
          type: string
        cacheStatus:
          type: string
        customField:
          type: string
        turnAroundTimeMSec:
          type: string
        transferTimeMSec:
          type: string
        cliIP:
          type: string
        statusCode:
          type: string
        reqHost:
          type: string
        reqMethod:
          type: string
        bytes:
          type: string
        tlsVersion:
          type: string
        UA:
          type: string
        queryStr:
          type: string
        rspContentLen:
          type: string
        rspContentType:
          type: string
        reqPath:
          type: string
        reqPort:
          type: string
        proto:
          type: string
        reqTimeSec:
          type: string
        cp:
          type: string
        reqId:
          type: string
        tlsOverheadTimeMSec:
          type: string
        objSize:
          type: string
        uncompressedSize:
          type: string
        overheadBytes:
          type: string
        totalBytes:
          type: string
        accLang:
          type: string
        cookie:
          type: string
        range:
          type: string
        referer:
          type: string
        xForwardedFor:
          type: string
        maxAgeSec:
          type: string
        reqEndTimeMSec:
          type: string
        errorCode:
          type: string
        dnsLookupTimeMSec:
          type: string
        billingRegion:
          type: string
        edgeIP:
          type: string
        securityRules:
          type: string
        serverCountry:
          type: string
        streamId:
          type: string
        asn:
          type: string
        breadcrumbs:
          type: string
    errorData:
      type: object
      description: >
        Detail of each error modeled based on the cos error and exceptions spec:  https://github.corp.ebay.com/commerceos/cos-error-and-exceptions/blob/master/error-and-exception-handling.md
      properties:
        errorId:
          example:
            4000: No User-Agent header
            4001: No X-EBAY-C-ENDUSERCTX header
            4002: No X-EBAY-C-TRACKING header
            4003: No Referer in header nor in post body
            4004: Illegal URL
            4005: No query parameter
            4006: No mkevt
            4007: Invalid mkevt
            4008: Invalid X-EBAY-C-ENDUSERCTX header
            4011: No page id
            5000: Internal Service Error
          type: number
          description: Value indicates type of error
        domain:
          type: string
          enum:
            - Marketing
        subdomain:
          type: string
          enum:
            - Tracking
        category:
          type: string
          example:
            REQUEST: Incorrect request e.g. auth, headers etc (Error Code 4xxx)
            APPLICATION: Service related runtime exception (Error Code 5xxx)
          enum:
            - REQUEST # Issues with the request e.g. auth, headers etc.
            - APPLICATION # application/runtime exception
        message:
          type: string
        longMessage:
          type: string
        inputRefIds:
          type: array
          items:
            type: string
        outputRefIds:
          type: array
          items:
            type: string
        parameters:
          type: array
          items:
            type: string
    errorModel:
      description: One or more error details
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/errorData'
