/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.app.raptor.chocolate.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelType {
  DEFAULT, EPN, DISPLAY, PAID_SEARCH, SOCIAL_MEDIA, PAID_SOCIAL, ROI, SITE_EMAIL, MRKT_EMAIL, SITE_MESSAGE_CENTER, MRKT_MESSAGE_CENTER, NATURAL_SEARCH, NOTIFICATION, MRKT_SMS, SITE_SMS, SEARCH_ENGINE_FREE_LISTINGS, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelType\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"symbols\":[\"DEFAULT\",\"EPN\",\"DISPLAY\",\"PAID_SEARCH\",\"SOCIAL_MEDIA\",\"PAID_SOCIAL\",\"ROI\",\"SITE_EMAIL\",\"MRKT_EMAIL\",\"SITE_MESSAGE_CENTER\",\"MRKT_MESSAGE_CENTER\",\"NATURAL_SEARCH\",\"NOTIFICATION\",\"MRKT_SMS\",\"SITE_SMS\",\"SEARCH_ENGINE_FREE_LISTINGS\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
