/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.app.raptor.chocolate.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum HttpMethod { 
  CONNECT, DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HttpMethod\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"symbols\":[\"CONNECT\",\"DELETE\",\"GET\",\"HEAD\",\"OPTIONS\",\"PATCH\",\"POST\",\"PUT\",\"TRACE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
