/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.app.raptor.chocolate.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ImkRvrTrckngMgvalueMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6442576634633558538L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ImkRvrTrckngMgvalueMessage\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"fields\":[{\"name\":\"rheosHeader\",\"type\":{\"type\":\"record\",\"name\":\"RheosHeader\",\"fields\":[{\"name\":\"eventCreateTimestamp\",\"type\":\"long\"},{\"name\":\"eventSentTimestamp\",\"type\":\"long\"},{\"name\":\"schemaId\",\"type\":\"int\"},{\"name\":\"eventId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"producerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},\"doc\":\"Rheos header - This is  mandatory for every schema in Rheos \"},{\"name\":\"rvr_id\",\"type\":\"long\"},{\"name\":\"event_dt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mgvalue\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mgvalue_rsn_cd\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cre_date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cre_user\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"upd_date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"upd_user\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"pk\":[\"rvr_id\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ImkRvrTrckngMgvalueMessage> ENCODER =
      new BinaryMessageEncoder<ImkRvrTrckngMgvalueMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ImkRvrTrckngMgvalueMessage> DECODER =
      new BinaryMessageDecoder<ImkRvrTrckngMgvalueMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ImkRvrTrckngMgvalueMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ImkRvrTrckngMgvalueMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ImkRvrTrckngMgvalueMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ImkRvrTrckngMgvalueMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ImkRvrTrckngMgvalueMessage from a ByteBuffer. */
  public static ImkRvrTrckngMgvalueMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Rheos header - This is  mandatory for every schema in Rheos  */
   private com.ebay.app.raptor.chocolate.avro.RheosHeader rheosHeader;
   private long rvr_id;
   private java.lang.String event_dt;
   private java.lang.String mgvalue;
   private java.lang.String mgvalue_rsn_cd;
   private java.lang.String cre_date;
   private java.lang.String cre_user;
   private java.lang.String upd_date;
   private java.lang.String upd_user;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ImkRvrTrckngMgvalueMessage() {}

  /**
   * All-args constructor.
   * @param rheosHeader Rheos header - This is  mandatory for every schema in Rheos 
   * @param rvr_id The new value for rvr_id
   * @param event_dt The new value for event_dt
   * @param mgvalue The new value for mgvalue
   * @param mgvalue_rsn_cd The new value for mgvalue_rsn_cd
   * @param cre_date The new value for cre_date
   * @param cre_user The new value for cre_user
   * @param upd_date The new value for upd_date
   * @param upd_user The new value for upd_user
   */
  public ImkRvrTrckngMgvalueMessage(com.ebay.app.raptor.chocolate.avro.RheosHeader rheosHeader, java.lang.Long rvr_id, java.lang.String event_dt, java.lang.String mgvalue, java.lang.String mgvalue_rsn_cd, java.lang.String cre_date, java.lang.String cre_user, java.lang.String upd_date, java.lang.String upd_user) {
    this.rheosHeader = rheosHeader;
    this.rvr_id = rvr_id;
    this.event_dt = event_dt;
    this.mgvalue = mgvalue;
    this.mgvalue_rsn_cd = mgvalue_rsn_cd;
    this.cre_date = cre_date;
    this.cre_user = cre_user;
    this.upd_date = upd_date;
    this.upd_user = upd_user;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rheosHeader;
    case 1: return rvr_id;
    case 2: return event_dt;
    case 3: return mgvalue;
    case 4: return mgvalue_rsn_cd;
    case 5: return cre_date;
    case 6: return cre_user;
    case 7: return upd_date;
    case 8: return upd_user;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rheosHeader = (com.ebay.app.raptor.chocolate.avro.RheosHeader)value$; break;
    case 1: rvr_id = (java.lang.Long)value$; break;
    case 2: event_dt = (java.lang.String)value$; break;
    case 3: mgvalue = (java.lang.String)value$; break;
    case 4: mgvalue_rsn_cd = (java.lang.String)value$; break;
    case 5: cre_date = (java.lang.String)value$; break;
    case 6: cre_user = (java.lang.String)value$; break;
    case 7: upd_date = (java.lang.String)value$; break;
    case 8: upd_user = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'rheosHeader' field.
   * @return Rheos header - This is  mandatory for every schema in Rheos 
   */
  public com.ebay.app.raptor.chocolate.avro.RheosHeader getRheosHeader() {
    return rheosHeader;
  }

  /**
   * Sets the value of the 'rheosHeader' field.
   * Rheos header - This is  mandatory for every schema in Rheos 
   * @param value the value to set.
   */
  public void setRheosHeader(com.ebay.app.raptor.chocolate.avro.RheosHeader value) {
    this.rheosHeader = value;
  }

  /**
   * Gets the value of the 'rvr_id' field.
   * @return The value of the 'rvr_id' field.
   */
  public java.lang.Long getRvrId() {
    return rvr_id;
  }

  /**
   * Sets the value of the 'rvr_id' field.
   * @param value the value to set.
   */
  public void setRvrId(java.lang.Long value) {
    this.rvr_id = value;
  }

  /**
   * Gets the value of the 'event_dt' field.
   * @return The value of the 'event_dt' field.
   */
  public java.lang.String getEventDt() {
    return event_dt;
  }

  /**
   * Sets the value of the 'event_dt' field.
   * @param value the value to set.
   */
  public void setEventDt(java.lang.String value) {
    this.event_dt = value;
  }

  /**
   * Gets the value of the 'mgvalue' field.
   * @return The value of the 'mgvalue' field.
   */
  public java.lang.String getMgvalue() {
    return mgvalue;
  }

  /**
   * Sets the value of the 'mgvalue' field.
   * @param value the value to set.
   */
  public void setMgvalue(java.lang.String value) {
    this.mgvalue = value;
  }

  /**
   * Gets the value of the 'mgvalue_rsn_cd' field.
   * @return The value of the 'mgvalue_rsn_cd' field.
   */
  public java.lang.String getMgvalueRsnCd() {
    return mgvalue_rsn_cd;
  }

  /**
   * Sets the value of the 'mgvalue_rsn_cd' field.
   * @param value the value to set.
   */
  public void setMgvalueRsnCd(java.lang.String value) {
    this.mgvalue_rsn_cd = value;
  }

  /**
   * Gets the value of the 'cre_date' field.
   * @return The value of the 'cre_date' field.
   */
  public java.lang.String getCreDate() {
    return cre_date;
  }

  /**
   * Sets the value of the 'cre_date' field.
   * @param value the value to set.
   */
  public void setCreDate(java.lang.String value) {
    this.cre_date = value;
  }

  /**
   * Gets the value of the 'cre_user' field.
   * @return The value of the 'cre_user' field.
   */
  public java.lang.String getCreUser() {
    return cre_user;
  }

  /**
   * Sets the value of the 'cre_user' field.
   * @param value the value to set.
   */
  public void setCreUser(java.lang.String value) {
    this.cre_user = value;
  }

  /**
   * Gets the value of the 'upd_date' field.
   * @return The value of the 'upd_date' field.
   */
  public java.lang.String getUpdDate() {
    return upd_date;
  }

  /**
   * Sets the value of the 'upd_date' field.
   * @param value the value to set.
   */
  public void setUpdDate(java.lang.String value) {
    this.upd_date = value;
  }

  /**
   * Gets the value of the 'upd_user' field.
   * @return The value of the 'upd_user' field.
   */
  public java.lang.String getUpdUser() {
    return upd_user;
  }

  /**
   * Sets the value of the 'upd_user' field.
   * @param value the value to set.
   */
  public void setUpdUser(java.lang.String value) {
    this.upd_user = value;
  }

  /**
   * Creates a new ImkRvrTrckngMgvalueMessage RecordBuilder.
   * @return A new ImkRvrTrckngMgvalueMessage RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder newBuilder() {
    return new com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder();
  }

  /**
   * Creates a new ImkRvrTrckngMgvalueMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ImkRvrTrckngMgvalueMessage RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder other) {
    return new com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder(other);
  }

  /**
   * Creates a new ImkRvrTrckngMgvalueMessage RecordBuilder by copying an existing ImkRvrTrckngMgvalueMessage instance.
   * @param other The existing instance to copy.
   * @return A new ImkRvrTrckngMgvalueMessage RecordBuilder
   */
  public static com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage other) {
    return new com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder(other);
  }

  /**
   * RecordBuilder for ImkRvrTrckngMgvalueMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ImkRvrTrckngMgvalueMessage>
    implements org.apache.avro.data.RecordBuilder<ImkRvrTrckngMgvalueMessage> {

    /** Rheos header - This is  mandatory for every schema in Rheos  */
    private com.ebay.app.raptor.chocolate.avro.RheosHeader rheosHeader;
    private com.ebay.app.raptor.chocolate.avro.RheosHeader.Builder rheosHeaderBuilder;
    private long rvr_id;
    private java.lang.String event_dt;
    private java.lang.String mgvalue;
    private java.lang.String mgvalue_rsn_cd;
    private java.lang.String cre_date;
    private java.lang.String cre_user;
    private java.lang.String upd_date;
    private java.lang.String upd_user;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rheosHeader)) {
        this.rheosHeader = data().deepCopy(fields()[0].schema(), other.rheosHeader);
        fieldSetFlags()[0] = true;
      }
      if (other.hasRheosHeaderBuilder()) {
        this.rheosHeaderBuilder = com.ebay.app.raptor.chocolate.avro.RheosHeader.newBuilder(other.getRheosHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.rvr_id)) {
        this.rvr_id = data().deepCopy(fields()[1].schema(), other.rvr_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.event_dt)) {
        this.event_dt = data().deepCopy(fields()[2].schema(), other.event_dt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mgvalue)) {
        this.mgvalue = data().deepCopy(fields()[3].schema(), other.mgvalue);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mgvalue_rsn_cd)) {
        this.mgvalue_rsn_cd = data().deepCopy(fields()[4].schema(), other.mgvalue_rsn_cd);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cre_date)) {
        this.cre_date = data().deepCopy(fields()[5].schema(), other.cre_date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cre_user)) {
        this.cre_user = data().deepCopy(fields()[6].schema(), other.cre_user);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.upd_date)) {
        this.upd_date = data().deepCopy(fields()[7].schema(), other.upd_date);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.upd_user)) {
        this.upd_user = data().deepCopy(fields()[8].schema(), other.upd_user);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ImkRvrTrckngMgvalueMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.rheosHeader)) {
        this.rheosHeader = data().deepCopy(fields()[0].schema(), other.rheosHeader);
        fieldSetFlags()[0] = true;
      }
      this.rheosHeaderBuilder = null;
      if (isValidValue(fields()[1], other.rvr_id)) {
        this.rvr_id = data().deepCopy(fields()[1].schema(), other.rvr_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.event_dt)) {
        this.event_dt = data().deepCopy(fields()[2].schema(), other.event_dt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mgvalue)) {
        this.mgvalue = data().deepCopy(fields()[3].schema(), other.mgvalue);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mgvalue_rsn_cd)) {
        this.mgvalue_rsn_cd = data().deepCopy(fields()[4].schema(), other.mgvalue_rsn_cd);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cre_date)) {
        this.cre_date = data().deepCopy(fields()[5].schema(), other.cre_date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cre_user)) {
        this.cre_user = data().deepCopy(fields()[6].schema(), other.cre_user);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.upd_date)) {
        this.upd_date = data().deepCopy(fields()[7].schema(), other.upd_date);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.upd_user)) {
        this.upd_user = data().deepCopy(fields()[8].schema(), other.upd_user);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'rheosHeader' field.
      * Rheos header - This is  mandatory for every schema in Rheos 
      * @return The value.
      */
    public com.ebay.app.raptor.chocolate.avro.RheosHeader getRheosHeader() {
      return rheosHeader;
    }

    /**
      * Sets the value of the 'rheosHeader' field.
      * Rheos header - This is  mandatory for every schema in Rheos 
      * @param value The value of 'rheosHeader'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setRheosHeader(com.ebay.app.raptor.chocolate.avro.RheosHeader value) {
      validate(fields()[0], value);
      this.rheosHeaderBuilder = null;
      this.rheosHeader = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rheosHeader' field has been set.
      * Rheos header - This is  mandatory for every schema in Rheos 
      * @return True if the 'rheosHeader' field has been set, false otherwise.
      */
    public boolean hasRheosHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'rheosHeader' field and creates one if it doesn't exist yet.
     * Rheos header - This is  mandatory for every schema in Rheos 
     * @return This builder.
     */
    public com.ebay.app.raptor.chocolate.avro.RheosHeader.Builder getRheosHeaderBuilder() {
      if (rheosHeaderBuilder == null) {
        if (hasRheosHeader()) {
          setRheosHeaderBuilder(com.ebay.app.raptor.chocolate.avro.RheosHeader.newBuilder(rheosHeader));
        } else {
          setRheosHeaderBuilder(com.ebay.app.raptor.chocolate.avro.RheosHeader.newBuilder());
        }
      }
      return rheosHeaderBuilder;
    }

    /**
     * Sets the Builder instance for the 'rheosHeader' field
     * Rheos header - This is  mandatory for every schema in Rheos 
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setRheosHeaderBuilder(com.ebay.app.raptor.chocolate.avro.RheosHeader.Builder value) {
      clearRheosHeader();
      rheosHeaderBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'rheosHeader' field has an active Builder instance
     * Rheos header - This is  mandatory for every schema in Rheos 
     * @return True if the 'rheosHeader' field has an active Builder instance
     */
    public boolean hasRheosHeaderBuilder() {
      return rheosHeaderBuilder != null;
    }

    /**
      * Clears the value of the 'rheosHeader' field.
      * Rheos header - This is  mandatory for every schema in Rheos 
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearRheosHeader() {
      rheosHeader = null;
      rheosHeaderBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'rvr_id' field.
      * @return The value.
      */
    public java.lang.Long getRvrId() {
      return rvr_id;
    }

    /**
      * Sets the value of the 'rvr_id' field.
      * @param value The value of 'rvr_id'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setRvrId(long value) {
      validate(fields()[1], value);
      this.rvr_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'rvr_id' field has been set.
      * @return True if the 'rvr_id' field has been set, false otherwise.
      */
    public boolean hasRvrId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'rvr_id' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearRvrId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'event_dt' field.
      * @return The value.
      */
    public java.lang.String getEventDt() {
      return event_dt;
    }

    /**
      * Sets the value of the 'event_dt' field.
      * @param value The value of 'event_dt'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setEventDt(java.lang.String value) {
      validate(fields()[2], value);
      this.event_dt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'event_dt' field has been set.
      * @return True if the 'event_dt' field has been set, false otherwise.
      */
    public boolean hasEventDt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'event_dt' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearEventDt() {
      event_dt = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'mgvalue' field.
      * @return The value.
      */
    public java.lang.String getMgvalue() {
      return mgvalue;
    }

    /**
      * Sets the value of the 'mgvalue' field.
      * @param value The value of 'mgvalue'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setMgvalue(java.lang.String value) {
      validate(fields()[3], value);
      this.mgvalue = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'mgvalue' field has been set.
      * @return True if the 'mgvalue' field has been set, false otherwise.
      */
    public boolean hasMgvalue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'mgvalue' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearMgvalue() {
      mgvalue = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'mgvalue_rsn_cd' field.
      * @return The value.
      */
    public java.lang.String getMgvalueRsnCd() {
      return mgvalue_rsn_cd;
    }

    /**
      * Sets the value of the 'mgvalue_rsn_cd' field.
      * @param value The value of 'mgvalue_rsn_cd'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setMgvalueRsnCd(java.lang.String value) {
      validate(fields()[4], value);
      this.mgvalue_rsn_cd = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'mgvalue_rsn_cd' field has been set.
      * @return True if the 'mgvalue_rsn_cd' field has been set, false otherwise.
      */
    public boolean hasMgvalueRsnCd() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'mgvalue_rsn_cd' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearMgvalueRsnCd() {
      mgvalue_rsn_cd = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cre_date' field.
      * @return The value.
      */
    public java.lang.String getCreDate() {
      return cre_date;
    }

    /**
      * Sets the value of the 'cre_date' field.
      * @param value The value of 'cre_date'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setCreDate(java.lang.String value) {
      validate(fields()[5], value);
      this.cre_date = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cre_date' field has been set.
      * @return True if the 'cre_date' field has been set, false otherwise.
      */
    public boolean hasCreDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cre_date' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearCreDate() {
      cre_date = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'cre_user' field.
      * @return The value.
      */
    public java.lang.String getCreUser() {
      return cre_user;
    }

    /**
      * Sets the value of the 'cre_user' field.
      * @param value The value of 'cre_user'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setCreUser(java.lang.String value) {
      validate(fields()[6], value);
      this.cre_user = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'cre_user' field has been set.
      * @return True if the 'cre_user' field has been set, false otherwise.
      */
    public boolean hasCreUser() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'cre_user' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearCreUser() {
      cre_user = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'upd_date' field.
      * @return The value.
      */
    public java.lang.String getUpdDate() {
      return upd_date;
    }

    /**
      * Sets the value of the 'upd_date' field.
      * @param value The value of 'upd_date'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setUpdDate(java.lang.String value) {
      validate(fields()[7], value);
      this.upd_date = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'upd_date' field has been set.
      * @return True if the 'upd_date' field has been set, false otherwise.
      */
    public boolean hasUpdDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'upd_date' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearUpdDate() {
      upd_date = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'upd_user' field.
      * @return The value.
      */
    public java.lang.String getUpdUser() {
      return upd_user;
    }

    /**
      * Sets the value of the 'upd_user' field.
      * @param value The value of 'upd_user'.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder setUpdUser(java.lang.String value) {
      validate(fields()[8], value);
      this.upd_user = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'upd_user' field has been set.
      * @return True if the 'upd_user' field has been set, false otherwise.
      */
    public boolean hasUpdUser() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'upd_user' field.
      * @return This builder.
      */
    public com.ebay.app.raptor.chocolate.avro.ImkRvrTrckngMgvalueMessage.Builder clearUpdUser() {
      upd_user = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ImkRvrTrckngMgvalueMessage build() {
      try {
        ImkRvrTrckngMgvalueMessage record = new ImkRvrTrckngMgvalueMessage();
        if (rheosHeaderBuilder != null) {
          record.rheosHeader = this.rheosHeaderBuilder.build();
        } else {
          record.rheosHeader = fieldSetFlags()[0] ? this.rheosHeader : (com.ebay.app.raptor.chocolate.avro.RheosHeader) defaultValue(fields()[0]);
        }
        record.rvr_id = fieldSetFlags()[1] ? this.rvr_id : (java.lang.Long) defaultValue(fields()[1]);
        record.event_dt = fieldSetFlags()[2] ? this.event_dt : (java.lang.String) defaultValue(fields()[2]);
        record.mgvalue = fieldSetFlags()[3] ? this.mgvalue : (java.lang.String) defaultValue(fields()[3]);
        record.mgvalue_rsn_cd = fieldSetFlags()[4] ? this.mgvalue_rsn_cd : (java.lang.String) defaultValue(fields()[4]);
        record.cre_date = fieldSetFlags()[5] ? this.cre_date : (java.lang.String) defaultValue(fields()[5]);
        record.cre_user = fieldSetFlags()[6] ? this.cre_user : (java.lang.String) defaultValue(fields()[6]);
        record.upd_date = fieldSetFlags()[7] ? this.upd_date : (java.lang.String) defaultValue(fields()[7]);
        record.upd_user = fieldSetFlags()[8] ? this.upd_user : (java.lang.String) defaultValue(fields()[8]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ImkRvrTrckngMgvalueMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<ImkRvrTrckngMgvalueMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ImkRvrTrckngMgvalueMessage>
    READER$ = (org.apache.avro.io.DatumReader<ImkRvrTrckngMgvalueMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
