/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.app.raptor.chocolate.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PublisherCacheEntry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PublisherCacheEntry\",\"namespace\":\"com.ebay.app.raptor.chocolate.avro\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"publisher_id\",\"type\":\"long\"},{\"name\":\"campaign_id\",\"type\":\"long\"}],\"pk\":[\"snapshot_id\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private long timestamp;
   private long publisher_id;
   private long campaign_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PublisherCacheEntry() {}

  /**
   * All-args constructor.
   */
  public PublisherCacheEntry(java.lang.Long timestamp, java.lang.Long publisher_id, java.lang.Long campaign_id) {
    this.timestamp = timestamp;
    this.publisher_id = publisher_id;
    this.campaign_id = campaign_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return publisher_id;
    case 2: return campaign_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: publisher_id = (java.lang.Long)value$; break;
    case 2: campaign_id = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'publisher_id' field.
   */
  public java.lang.Long getPublisherId() {
    return publisher_id;
  }

  /**
   * Sets the value of the 'publisher_id' field.
   * @param value the value to set.
   */
  public void setPublisherId(java.lang.Long value) {
    this.publisher_id = value;
  }

  /**
   * Gets the value of the 'campaign_id' field.
   */
  public java.lang.Long getCampaignId() {
    return campaign_id;
  }

  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(java.lang.Long value) {
    this.campaign_id = value;
  }

  /** Creates a new PublisherCacheEntry RecordBuilder */
  public static com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder newBuilder() {
    return new com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder();
  }
  
  /** Creates a new PublisherCacheEntry RecordBuilder by copying an existing Builder */
  public static com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder other) {
    return new com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder(other);
  }
  
  /** Creates a new PublisherCacheEntry RecordBuilder by copying an existing PublisherCacheEntry instance */
  public static com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder newBuilder(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry other) {
    return new com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder(other);
  }
  
  /**
   * RecordBuilder for PublisherCacheEntry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PublisherCacheEntry>
    implements org.apache.avro.data.RecordBuilder<PublisherCacheEntry> {

    private long timestamp;
    private long publisher_id;
    private long campaign_id;

    /** Creates a new Builder */
    private Builder() {
      super(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.publisher_id)) {
        this.publisher_id = data().deepCopy(fields()[1].schema(), other.publisher_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[2].schema(), other.campaign_id);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PublisherCacheEntry instance */
    private Builder(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry other) {
            super(com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.publisher_id)) {
        this.publisher_id = data().deepCopy(fields()[1].schema(), other.publisher_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[2].schema(), other.campaign_id);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'timestamp' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'publisher_id' field */
    public java.lang.Long getPublisherId() {
      return publisher_id;
    }
    
    /** Sets the value of the 'publisher_id' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder setPublisherId(long value) {
      validate(fields()[1], value);
      this.publisher_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'publisher_id' field has been set */
    public boolean hasPublisherId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'publisher_id' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder clearPublisherId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'campaign_id' field */
    public java.lang.Long getCampaignId() {
      return campaign_id;
    }
    
    /** Sets the value of the 'campaign_id' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder setCampaignId(long value) {
      validate(fields()[2], value);
      this.campaign_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'campaign_id' field has been set */
    public boolean hasCampaignId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'campaign_id' field */
    public com.ebay.app.raptor.chocolate.avro.PublisherCacheEntry.Builder clearCampaignId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PublisherCacheEntry build() {
      try {
        PublisherCacheEntry record = new PublisherCacheEntry();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.publisher_id = fieldSetFlags()[1] ? this.publisher_id : (java.lang.Long) defaultValue(fields()[1]);
        record.campaign_id = fieldSetFlags()[2] ? this.campaign_id : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
